### ISSUE TITLE
Not possible to install pyjnius 1.1.4 anymore - failing to install BioPax dependency

### ISSUE THREAD

**Issue by guerrerosimonl** [sorgerlab/indra#1020]
Hello again!

Apparently, it is not possible anymore to install version 1.1.4 of pyjnius anymore, but installing the latest version, and then trying to install Biopax dependency, I get this error:   

 ERROR: Command errored out with exit status 1:
     command: 'C:\Users\guerrerosimonl\AppData\Local\Continuum\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GUERRE~1\\AppData\\Local\\Temp\\pip-install-9ukv17jk\\pyjnius\\setup.py'"'"'; __file__='"'"'C:\\Users\\GUERRE~1\\AppData\\Local\\Temp\\pip-install-9ukv17jk\\pyjnius\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\GUERRE~1\AppData\Local\Temp\pip-install-9ukv17jk\pyjnius\pip-egg-info'
         cwd: C:\Users\GUERRE~1\AppData\Local\Temp\pip-install-9ukv17jk\pyjnius\
    Complete output (19 lines):
    warning: [options] bootstrap class path not set in conjunction with -source 6
    error: Source option 6 is no longer supported. Use 7 or later.
    error: Target option 6 is no longer supported. Use 7 or later.
    C:\Program Files\Java\jdk-13.0.1\bin
    WARNING: Not able to assign machine() = AMD64 to a cpu value!
             Using cpu = 'i386' instead!
    JDK_HOME: C:\Program Files\Java\jdk-13.0.1

    JRE_HOME: None

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\GUERRE~1\AppData\Local\Temp\pip-install-9ukv17jk\pyjnius\setup.py", line 240, in <module>
        compile_native_invocation_handler(JDK_HOME, JRE_HOME)
      File "C:\Users\GUERRE~1\AppData\Local\Temp\pip-install-9ukv17jk\pyjnius\setup.py", line 94, in compile_native_invocation_handler
        join('jnius', 'src', 'org', 'jnius', 'NativeInvocationHandler.java')
      File "C:\Users\guerrerosimonl\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Program Files\\Java\\jdk-13.0.1\\bin\\javac.exe', '-target', '1.6', '-source', '1.6', 'jnius\\src\\org\\jnius\\NativeInvocationHandler.java']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

How can I fix it? Thanks!

Laura

**Comment by bgyori** [comment]
I just checked and pyjnius 1.1.4 is in fact still available, here is the specific downloadable file: https://pypi.org/project/pyjnius/1.1.4/#files. What happened when you did
```
pip install cython
pip install pyjnius==1.1.4
```
per the instructions at https://indra.readthedocs.io/en/latest/installation.html#pyjnius?

**Comment by bgyori** [comment]
I also found that Pyjnius provides additional details for installing on Windows which may be relevant: https://pyjnius.readthedocs.io/en/stable/installation.html#installation-for-windows

Finally, I think you might have a much easier time just using the Dockerized deployment of INDRA that doesn't require any setup: https://github.com/sorgerlab/indra#indra-docker

**Comment by bgyori** [comment]
With the above recommendations about installing jnius on Windows or using the Docker container, I'll close this issue.
