### ISSUE TITLE
Calculating belief score based on various statements from one paper?

### ISSUE THREAD

**Issue by bernice493** [sorgerlab/indra#1047]
Dear Benjamin,
We are using INDRA to extra networks of interactions. So far the results are promising and we hope to be able to publish our results in a peer-reviewed paper. 
However, there is one issue that we are unsure of: we understand INDRA calculates the belief score based on the number of times a statement is repeated (and the knowledge source, but in our case we use only one knowledge source hence the BS is determined solely by the number of evidences). 
However, it appears that INDRA is not considering whether the statements come from the same pmid or not. We think it would be better to count all the repeated statements from a single pmid as only 1 since, otherwise, the evidence can be big (BS > 0.91) but still based on only 1 paper. 
Have you considered this and is there a solution? 
Kind regards,
Bernice

**Comment by bgyori** [comment]
Hi Bernice, yes, yo are right that the default belief engine does not take into account what PMIDs the evidences for a statement come from. I agree that it may be reasonable to assume that there is some systematic error associated with any single paper, and therefore, having a component in belief calculations that accounts for the "diversity" of PMIDs could make sense. On a software level, the way to achieve that is to implement a subclass of the BeliefScorer class (https://github.com/sorgerlab/indra/blob/master/indra/belief/__init__.py#L27) to replace the default SimpleScorer (https://github.com/sorgerlab/indra/blob/master/indra/belief/__init__.py#L73). By overriding the `score_statement` method, you can implement assumptions different from default.

**Comment by bernice493** [comment]
Thank you very much Benjamin. We managed now. Regards,
Bernice
