### ISSUE TITLE
local instance of REACH

### ISSUE THREAD

**Issue by guerrerosimonl** [sorgerlab/indra#1048]
Hi!

Would it be possible to ask for an user-friendly manual to set a local instance of REACH with the aim of applying the INDRA offline reading? 

Our team would love to set up this option but we are struggling. 

Thanks!

**Comment by bgyori** [comment]
Hi @guerrerosimonl, okay, we will add additional documentation at https://indra.readthedocs.io/en/latest/modules/sources/reach/index.html#reach-indra-sources-reach to describe ways in which REACH can be integrated with INDRA, and how to set up and run each of those.

**Comment by bgyori** [comment]
Just an update: we have been working on this for the last couple of weeks and have an open PR to improve the REACH API of INDRA and significantly extend the documentation: https://github.com/sorgerlab/indra/pull/1053. Currently, there are still some technical issues with the latest version of REACH so we are waiting a bit before merging the PR. Nevertheless, you can read the new documentation before it's merged here: https://github.com/sorgerlab/indra/pull/1053/files#diff-c6d849dc12fcdb04a51bd0ea1c11f894. In particular, I want to call your attention to the heading "1. INDRA communicating with a locally running REACH Server" as the preferred mode of integration.

**Comment by guerrerosimonl** [comment]
Thank you!!

**Comment by cannin** [comment]
@guerrerosimonl I was able to get offline reading to work with the Docker container with the following:

```
url = "http://127.0.0.1:8080/reach/process_text"

payload = {"text": "GRB2 binds SHC.", "offline": True}
headers = {'content-type': 'application/json', 'accept': 'application/json'}

r = requests.post(url, data=json.dumps(payload), headers=headers)
print(r.status_code, r.reason)
print(r.json())
```

**Comment by bgyori** [comment]
Yes, @cannin's approach also works, which assumes the INDRA Docker is running the INDR API locally.

**Comment by bgyori** [comment]
We have been working on various updates in REACH and INDRA to improve the integration, and have overhauled the documentation to describe the various forms of integration with their advantages and disadvantages. The recommended approach for using REACH via INDRA is currently the first heading here: "INDRA communicating with a locally running REACH Server " https://indra.readthedocs.io/en/latest/modules/sources/reach/index.html#indra-communicating-with-a-locally-running-reach-server-indra-sources-reach-api. This does not require setting up pyjnius which has proven to be difficult on some platforms.
