### ISSUE TITLE
Question on function of map_sequence

### ISSUE THREAD

**Issue by bernice493** [sorgerlab/indra#1056]
Dear Benjamin,

We have applied different filters to the generated INDRA statements, e.g. filter_no_hypothesis, or map_grounding. We have also applied the map_sequence filter because in a previous issue-response you proposed to use it. However, we struggle to understand what this function exactly entails. We read both the map_sequence instructions, and the information on SiteMapper class but it did not help. Could you perhaps shortly elaborate?

Regards,
Bernice

**Comment by bgyori** [comment]
That function maps amino acid positions referenced in INDRA Statements to correct for common inconsistencies in site positions with respect to the reference sequence of a protein. The test here illustrates how it works: https://github.com/sorgerlab/indra/blob/master/indra/tests/test_assemble_corpus.py#L349-L361. Per the test, assume a Statement references the amino acid site T182 on MAPK1. The map_sequence function corrects this to T185 which is the correct site on the reference sequence. To do this, INDRA invokes the `protmapper` package which is documented here: https://github.com/indralab/protmapper/ with the preprint here describing the detailed methodology of how mappings are performed: https://www.biorxiv.org/content/10.1101/822668v3.

**Comment by bernice493** [comment]
Thank you, it's very clear now.
