### ISSUE TITLE
BEL processor grounding for chemicals, processes and name standardization

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#107]
INDRA internally uses CHEBI IDs, MESH IDs and GO IDs for chemicals and processes, respectively. However, BEL Statements provide these IDs in the form of string names. There are resource files defining the mapping between names used in BEL and database entry IDs: http://resource.belframework.org/belframework/1.0/equivalence/
To start with, we can integrate BEL-specific maps for only these 3 namespaces which amounts to < 10 MB extra in resource files. Later, a more systemic solution is needed to handle all remaining name spaces.

**Comment by cthoyt** [comment]
Is this solved with the PyBEL processor?

**Comment by bgyori** [comment]
Fixed in #865
