### ISSUE TITLE
de-duplication problem

### ISSUE THREAD

**Issue by guerrerosimonl** [sorgerlab/indra#1080]
Hi!

I found a problem in the deduplication during preassembly. For example, I have the same statement (glyphosate inhibits aroA) from two different papers (22870190 and 28751654), but one of them annotates glyphosate with the first capital letter, and the other one all in lower case. Even though they re both identified with the same PubChem, at the final graph they are still shown as two different agents. 

I tried the ground mapping solution explained at issue #1059 but it didn't work.

Is there any solution for this?

Thank you so much again!

Laura

**Comment by bgyori** [comment]
Hi, this is due to the fact that INDRA currently doesn't implement chemical name standardization for entities that aren't grounded to or mappable to ChEBI. Among other things, the grounding mapping process attempts to map the given PubChem entry to ChEBI and then find its standard name. But if there is no such mapping, the name remains unchanged. Could you please share what the PubChem ID is that is assigned to glyphosate?

**Comment by guerrerosimonl** [comment]
For glyphosate the PubChem ID in our results is 3857.

And we have the same kind of problem with malathion with PubChem 4004.

**Comment by bgyori** [comment]
Here is a test I just did to see what happens:
```
In [1]: from indra.statements import Agent, Inhibition                                                                
In [2]: st1 = Inhibition(Agent('glyphosate', db_refs={'PUBCHEM': '3857'}), Agent('aroA'))                             
In [3]: st2 = Inhibition(Agent('Glyphosate', db_refs={'PUBCHEM': '3857'}), Agent('aroA'))                             
In [4]: from indra.tools import assemble_corpus as ac                                                                 
In [5]: stmts_out = ac.map_grounding([st1, st2])                                                                      
In [6]: stmts_out[0]                                                                                                  
Out[6]: Inhibition(2-amino-3-phosphonopropanoic acid(), aroA())
In [7]: stmts_out[1]                                                                                                  
Out[7]: Inhibition(2-amino-3-phosphonopropanoic acid(), aroA())
In [8]: stmts_out[0].subj.db_refs                                                                                     
Out[8]: {'PUBCHEM': '3857', 'CHEBI': 'CHEBI:28388'}
In [9]: stmts_out[1].subj.db_refs                                                                                     
Out[9]: {'PUBCHEM': '3857', 'CHEBI': 'CHEBI:28388'}
In [10]: stmts_assembled = ac.run_preassembly(stmts_out)                                                              
INFO: [2020-04-21 15:23:36] indra.tools.assemble_corpus - Combining duplicates on 2 statements...
INFO: [2020-04-21 15:23:36] indra.tools.assemble_corpus - 1 unique statements
INFO: [2020-04-21 15:23:36] indra.tools.assemble_corpus - Combining related on 1 statements...
INFO: [2020-04-21 15:23:36] indra.preassembler - Grouping Inhibition (1)
INFO: [2020-04-21 15:23:36] indra.tools.assemble_corpus - Filtering 1 statements for top-level...
INFO: [2020-04-21 15:23:36] indra.tools.assemble_corpus - 1 statements after filter...
INFO: [2020-04-21 15:23:36] indra.tools.assemble_corpus - 1 top-level statements
In [11]: stmts_assembled                                                                                              
Out[11]: [Inhibition(2-amino-3-phosphonopropanoic acid(), aroA())]
```
As you see, 3857 from PUBCHEM is mapped to CHEBI, the name of the Agent is standardized, and when running preassembly, the two statements are combined into a single one. So unless there is some additional detail that my test didn't capture, as long as you run `map_grounding` and `run_preassembly`, the result looks OK.

**Comment by guerrerosimonl** [comment]
Okay, when I perform the same test than you I get already this different:

stmts_out[0]
Out[6]: Inhibition(glyphosate(), aroA())
stmts_out[1]
Out[7]: Inhibition(Glyphosate(), aroA())

Do you have any idea of what can I be doing wrong?

Thanks again!

**Comment by bgyori** [comment]
The only thing I can think of is that you have an older version of INDRA and that this mapping happened to be added recently. Try installing INDRA from the latest Github master as
```
pip install git+https://github.com/sorgerlab/indra.git
```
and see if that solves this issue.

**Comment by guerrerosimonl** [comment]
YES! That was it. Thank you so much!

Laura
