### ISSUE TITLE
Adding ontology files in new release

### ISSUE THREAD

**Issue by sanyabt** [sorgerlab/indra#1113]
Hi, I was previously using INDRA's hierarchy manager to include ontology files (such as Disease Ontology). I see in the new release that the hierarchy manager has been deprecated. Is it replaced by the new indra.ontology module? If so, I would be grateful for any tutorials for implementing it and adding my own ontology files. 

Use case: We are using INDRA to extract predications over literature and constructing a knowledge graph with related ontologies.

**Comment by bgyori** [comment]
Hi @sanyabt, thanks for reaching out, yes, on the latest master, the `indra.preassembler.hierarchy_manager.HierarchyManager` class has been replaced by the `indra.ontology.IndraOntology` class.

The generic `IndraOntology` class is also subclassed into an ontology specific to biology applications in `indra.ontology.bio.BioOntology`. This `BioOntology` class contains nodes of the following name spaces: HGNC, UP, FPLX, CHEBI, DOID (this is the Disease Ontology which you mentioned), EFO, HP, MESH, GO, MIRBASE. It also contains `xrefs` (i.e., equivalent relations) between nodes in these name spaces, and `isa`/`partof` hierarchical relationships among these nodes.

If you want to build a custom ontology, you can either subclass the generic `IndraOntology` class and add nodes/edges from scratch, or you can subclass the `BioOntology` and make specific modifications to what is already implemented in there. Happy to help either way if you have questions!

**Comment by sanyabt** [comment]
Thank you so much for clarifying! Am I correct in assuming that using the bio_ontology is primarily an assembly step in the INDRA stack and there isn't a way to explore the ontology otherwise?

**Comment by bgyori** [comment]
Yes, it can be (and is!) used independently of the pre-assembly process. For instance, you can try
```python
In [1]: from indra.ontology.bio import bio_ontology
In [4]: children = bio_ontology.get_children('DOID', 'DOID:3133')               
In [5]: children                                                                
Out[5]: 
[('DOID', 'DOID:5230'),
 ('DOID', 'DOID:13269'),
 ('DOID', 'DOID:13270'),
 ('DOID', 'DOID:4346'),
 ('DOID', 'DOID:3890'),
 ('DOID', 'DOID:3132')]
In [6]: bio_ontology.get_name('DOID', 'DOID:3133')                              
Out[6]: 'acute porphyria'
In [7]: bio_ontology.get_mappings('DOID', 'DOID:3133')                          
Out[7]: [('MESH', 'D017094')]
```
etc. The IndraOntology is actually a subclass of networkx.DiGraph so you can do anything with it that you would normally do with such a networkx graph. Let me know if you have other questions!

**Comment by sanyabt** [comment]
Wonderful, thank you so much!

**Comment by bgyori** [comment]
Great, I'll close the issue for now.
