### ISSUE TITLE
Grounding EIDOS text with bio_ontology

### ISSUE THREAD

**Issue by sanyabt** [sorgerlab/indra#1121]
Hi @bgyori, following up from the issue created on the EIDOS repo (https://github.com/clulab/eidos/issues/884). I want to use the API call https://indra.readthedocs.io/en/latest/modules/sources/eidos/index.html#indra.sources.eidos.api.process_text_bio to get the groundings for entities.

Do I need gilda installed locally for the grounding to work? Any other tips on the workflow to ground texts from EIDOS using bio_ontology? Thanks so much.

**Comment by bgyori** [comment]
Hi @sanyabt, first of all, yes, Gilda can be installed simply as `pip install gilda`. The  functions `process_text_bio` and `process_json_bio` in the INDRA EIDOS API processes Eidos output, in particular, looking for causal relations (not standalone events or associations) and extracts them as Activation and Inhibition statements with Agent arguments grounded to biomedical ontologies. So if that is what you are looking for, you can just use one of these functions.

If your goal is to get a list of grounded _entities_, not _relations/statements_, the workflow might be a little bit different, if that's the case, I can follow up with some suggestions.

**Comment by sanyabt** [comment]
@bgyori sorry if my questions were ambiguous, the latter part of your reply is correct. Our goal with EIDOS is to get grounded entities - preferably with the bio_ontology.

**Comment by bgyori** [comment]
Okay, I understand, I think the easiest solution would be if we add a function to the API called `process_text_bio_entities` or `process_json_bio_entities` which produces a list of grounded entities represented as INDRA Agents based on all the individual entities that Eidos produces from a given text (independent of whether they are part of causal relations or not). This function will be useful for our work too so I'll try to add it today.

**Comment by bgyori** [comment]
Okay, I added both functions described above. The output is a list of INDRA Agents all of which have db_refs entries as follows:
- `TEXT`: the original, unchanged entity text based on the boundaries Eidos found
- `TEXT_NORM`: the normalized / canonicalized entity text that Eidos found
- any other name spaces (e.g., `MESH`, `CHEBI`, etc.): groundings found by Gilda based on the `TEXT_NORM` entry

**Comment by sanyabt** [comment]
Thank you so much @bgyori! Will add to my script this weekend.
