### ISSUE TITLE
Question on filtering INDRA Statements

### ISSUE THREAD

**Issue by PritiShaw** [sorgerlab/indra#1141]
Hi
I wanted to know if there is any method to **filter statements on the basis of source_api(s)** (eg REACH).
I checked documentation but could not find any

At present I have converted Statements to json using `from indra.statements.statements import stmts_to_json` and proceeded accordingly.
```
        "evidence": [
            {
                "source_api": "reach",
                "pmid": "28972042",
                "text": "TMCO1 dysregulates cell cycle progression via suppression of the AKT pathway, and S60 of the TMCO1 protein is crucial for its tumor suppressor roles.",
                "annotations": {
                    "found_by": "Negative_activation_syntax_1_verb",
                    "agents": {
                        "raw_text": [
                            "TMCO1",
                            "cell cycle"
                        ]
                    },
```

A possible way of implementing an independent filter function could be similar to [JSONPath](https://github.com/h2non/jsonpath-ng) as suggested by @cannin [here](https://github.com/cannin/enhance_nlp_interaction_network_gsoc2020/issues/10#issuecomment-656947744).

**Comment by bgyori** [comment]
Yes, there is such a filter documented here:  https://indra.readthedocs.io/en/latest/modules/tools/index.html#indra.tools.assemble_corpus.filter_evidence_source, it allows you to filter to statements coming from a specific set of sources (or the inverse).

**Comment by bgyori** [comment]
Also may be relevant that the same filter is available through the REST API as documented here http://api.indra.bio:8000/, under the "Preassembly" heading.
