### ISSUE TITLE
SOS: Save our Signor

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#1175]
It appears that there's no entry in the `packages` list in https://github.com/sorgerlab/indra/blob/master/setup.py for `'indra.sources.signor'`. This means if you install indra with `pip install indra` then in the python console type

```python
import indra.sources.signor
```

You get an `ImportError`. Was this previously known?

**Comment by bgyori** [comment]
That's really odd! It may have gone missing accidentally or was never there, I'll fix it.

**Comment by bgyori** [comment]
If you're going to get content from Signor, I suggest using the branch at #1172 which makes a number of updates to the processor to adapt to the latest Signor format, and fix some db_refs/text_refs invalidities.
