### ISSUE TITLE
Issue Setting Up REACHPATH to Run REACH Locally with JAR (and Alternative Solution)

### ISSUE THREAD

**Issue by cannin** [sorgerlab/indra#1188]
This might be a wontfix issue, but I had issues setting up the REACHPATH using os.environ() with INDRA 1.18.0 resulting in the necessary classes not being found. I ended up with this solution that might be helpful in the documentation. 

```
import jnius_config

reach_jar_path = "CHANGE_ME/reach/target/scala-2.11/reach-1.6.0-FAT.jar"

jnius_config.add_classpath(reach_jar_path)

from indra.sources import reach
from indra.statements.statements import stmts_to_json_file, stmts_to_json

DO_STUFF 
```

**Comment by bgyori** [comment]
Hi @cannin, we have recently significantly extended the documentation on this, and the current recommended approach to using REACH with INDRA is "INDRA communicating with a locally running REACH Server" (https://indra.readthedocs.io/en/latest/modules/sources/reach/index.html#indra-communicating-with-a-locally-running-reach-server-indra-sources-reach-api). This is much easier to set up than the JAR-based integration and has many other advantages.

Having said that, I suspect the os.environ() setting of REACHPATH conflicted with CLASSPATH in a way that INDRA couldn't resolve it and so your explicit setting of the jnius worked around that.

**Comment by bgyori** [comment]
Just re-read that part of the docs on the JAR-based reading, in this section: https://indra.readthedocs.io/en/latest/modules/sources/reach/index.html#indra-using-a-reach-jar-through-a-python-java-bridge-indra-sources-reach-reader
```
Set the absolute path to this file on the REACHPATH environmental variable and then append REACHPATH to the CLASSPATH environmental variable (entries are separated by colons).
```
Did you do the second part of setting the CLASSPATH?

**Comment by cannin** [comment]
This is what confused me about the documentation. What is REACHPATH being used for? Only to set the CLASSPATH? Which in my usage appears to be the case. If so, why not just set the CLASSPATH? Hence I started to look for a solution to "add" the classpath with add_classpath() as opposed to the logic of checking if CLASSPATH exists and then either setting it or doing a string concatenation on the CLASSPATH on the existing value. It seemed more "cleaner" especially if Java use is isolated to just running REACH in the project.

**Comment by bgyori** [comment]
That's a fair point. The reason it is documented this way is that we have multiple Java dependencies that have _conflicting dependencies_ and therefore cannot simultaneously be on the CLASSPATH. By setting both REACHPATH and separately CLASSPATH (which can include other JARs as well), INDRA can automatically launch jnius with the right settings in any scenario.

**Comment by bgyori** [comment]
As for your point about setting the CLASSPATH, doing
```
export CLASSPATH=$CLASSPATH:/path/to/some.jar
```
will always work, irrespective of whether CLASSPATH already exists or not, so you can use that without more complex logic for checking its status.

**Comment by cannin** [comment]
Thanks. Closing issue. The comments here might help someone address CLASSPATH issues.
