### ISSUE TITLE
Grounding + duplicate recognition issue

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#119]
Consider the following two statements:
- Complex([actin(db_refs={'TEXT': 'actin'}), ATP()])
- Complex([Actin(db_refs={'TEXT': 'Actin'}), ATP()])

The grounding mapper, using the current state of the map, produces:
- Complex([Actin(db_refs={'TEXT': 'actin', 'IP': 'IPR004000', 'BE': 'Actin', 'MESH': 'D000199'}), ATP()])
- Complex([Actin(db_refs={'TEXT': 'Actin'}), ATP()])

Since `Actin` is not in the grounding map but `actin` is, the first Statement gets mapped and the second one doesn't. But the names of both agents become `Actin`. (Note that this issue exists irrespective of grounding mapping, simply if two identically named entities have different grounding. But grounding mapping exposes many actual instances of this issue.)

The next step in assembly is typically `combine_duplicates`, which looks only at the `agent.matches_key()` property which, without any further Agent properties is just `agent.name`. So it concludes that the two statements are the same and chooses one of them as the _primary_ statement. _Importantly, however, it chooses the primary statements in an arbitrary order_.
Consequently, sometimes a grounded version of Actin, and other times an ungrounded version of Actin is preserved at the unique statements level. This is already, in itself a problem since one often filters based on grounding. But let's go further.

The next step is typically `combine_related`, which looks at grounding to figure out how things relate in the entity hierarchy. If the grounded statement ends up as the primary unique then it is grouped with all other grounded Actin statements. However, if the ungrounded statement ends up as the primary unique then it will not be grouped with grounded versions of Actin. This distinction can make a difference, and can result in a non-deterministic set of top-level statements. I observed this behavior (i.e. varying number of top-level statements in repeated runs) for several large statement sets.

**Comment by johnbachman** [comment]
Good find! Do you think this means we need to take the plunge to do matching based on grounding?

**Comment by bgyori** [comment]
Solved in a375444eec2a98eb9886b11fd84f6666fe2f943e
