### ISSUE TITLE
REACH ApiServer configuration

### ISSUE THREAD

**Issue by sanyabt** [sorgerlab/indra#1248]
Hi @bgyori, hope you're well. I recently updated REACH on my local system and am trying to process full texts with INDRA using REACH. I am using the recommended approach of "INDRA communicating with a locally running REACH Server " following the instructions here - https://indra.readthedocs.io/en/latest/modules/sources/reach/index.html#indra-communicating-with-a-locally-running-reach-server-indra-sources-reach-api.

However, I am running into issues with texts longer than 2048 characters and am unable to find the setting to change it - the file _export/src/main/resources/reference.conf_ does not have a _max-uri-length_ parameter as far as I can tell. Have the instructions been updated somewhere? Please let me know.

Thanks!

**Comment by bgyori** [comment]
Yes, I recently wrote some additional instructions to work around this issue, see https://indra.readthedocs.io/en/latest/modules/sources/reach/index.html#indra-communicating-with-a-locally-running-reach-server-indra-sources-reach-api:

```
One limitation here is that the REACH sever is configured by default to limit the input to 2048 characters. To change this, edit the file export/src/main/resources/reference.conf in your local reach clone folder and add

http {
  server {
  // ...
  parsing {
    max-uri-length = 256k
  }
  // ...
  }
}
to increase the character limit.
```

**Comment by bgyori** [comment]
Yes, that parameter isn't there to begin with, you have to add it. Per the instructions I wrote, in this position:
```
http {
  server {
  // ...
  parsing {
    max-uri-length = 256k
  }
  // ...
  }
}
```

You should already see the `http` block and the `server` block within it. Then you can add
```
  parsing {
    max-uri-length = 256k
  }
```
in there.

**Comment by sanyabt** [comment]
Ah, I get it now. Thanks so much!
