### ISSUE TITLE
Obsolete Python 2 print statements in run_combined.py

### ISSUE THREAD

**Issue by catskillsresearch** [sorgerlab/indra#1282]
File run_combined.py in various iterations contains old style print statements which create problems in Python install:

```
Extracting indra-1.19.0-py3.7.egg to /home/catskills/anaconda3/lib/python3.7/site-packages
  File "/home/catskills/anaconda3/lib/python3.7/site-packages/indra-1.19.0-py3.7.egg/indra/benchmarks/assembly_eval/combine4/run_combined.py", line 23
    print 'Processing %s...' % pmcid
                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Processing %s...' % pmcid)?
```

I suggest you add a parentheses around the arguments to each of these print statements to smooth the install.

**Comment by bgyori** [comment]
Hi @catskillsresearch, thanks, indeed that part of the code is pretty old and isn't part of the reusable code base so it hasn't been updated. I'm surprised that it causes any issues at the level of installation. Perhaps conda behaves differently in this regard compared to pip where we haven't observed this issue. Could you send what command you ran that resulted in this error? Thanks!

**Comment by catskillsresearch** [comment]
The commands I used were:

```
git clone https://github.com/sorgerlab/indra.git
cd indra
python setup.py install
```
and the above item showed up in the install dialog.  Here is a larger clip:

```
byte-compiling build/bdist.linux-x86_64/egg/indra/databases/ndex_client.py to ndex_client.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/indra/databases/go_client.py to go_client.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/indra/databases/cbio_client.py to cbio_client.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/indra/databases/context_client.py to context_client.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/indra/benchmarks/assembly_eval/combine4/analyze4way.py to analyze4way.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/indra/benchmarks/assembly_eval/combine4/run_combined.py to run_combined.cpython-37.pyc
  File "build/bdist.linux-x86_64/egg/indra/benchmarks/assembly_eval/combine4/run_combined.py", line 23
    print 'Processing %s...' % pmcid
                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Processing %s...' % pmcid)?

byte-compiling build/bdist.linux-x86_64/egg/indra/benchmarks/assembly_eval/batch4/run_trips_eval.py to run_trips_eval.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/indra/benchmarks/assembly_eval/batch4/run_reach_eval.py to run_reach_eval.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/indra/benchmarks/assembly_eval/batch4/assembly_eval.py to assembly_eval.cpython-37.pyc
```
So it doesn't stop the build but it does complain.

**Comment by bgyori** [comment]
I see, thanks! I would suggest that you try
```
git clone https://github.com/sorgerlab/indra.git
cd indra
pip install -e .
```
which will generally behave much better than running setup.py directly. There is a bit more description on installation options this page: https://indra.readthedocs.io/en/latest/installation.html#installing-via-github.

In any case, now that you brought it up, it would be better to move out these old benchmark scripts into the `indra_apps` repo so we'll look into that.
