### ISSUE TITLE
Clarify species/taxonomy annotations for SIGNOR 

### ISSUE THREAD

**Issue by helena-balabin** [sorgerlab/indra#1292]
When I was going through the species annotations of the statements, I've stumbled across a number of statements that are labelled with **{"TAXONOMY": "-1"}**, such as: 

`{"type": "ActiveForm", "agent": {"name": "TNK2", "mods": [{"mod_type": "phosphorylation", "residue": "Y", "position": "284", "is_modified": true}], "db_refs": {"UP": "Q07912", "HGNC": "19297"}}, "activity": "activity", "is_active": true, "belief": 1, "evidence": [{"source_api": "signor", "pmid": "16472662", "source_id": "SIGNOR-251184", "text": "Purified ACK1 undergoes autophosphorylation at Tyr284, and autophosphorylation increases kinase activity", "annotations": {"SEQUENCE": "LPQNDDHyVMQEHRK", "MODULATOR_COMPLEX": null, "TARGET_COMPLEX": null, "MODIFICATIONA": null, "MODASEQ": null, "MODIFICATIONB": null, "MODBSEQ": null, "NOTES": null, "ANNOTATOR": null}, "epistemics": {"direct": true}, "context": {"species": {"name": null, "db_refs": {"TAXONOMY": "-1"}}, "type": "bio"}, "text_refs": {"PMID": "16472662"}, "source_hash": 7149895887045473071}], "id": "2a1446c1-3338-4f67-96f2-abeab4d0b714"}`

All of the respective statements come from SIGNOR, and @cthoyt assumes that it's linked to the SIGNOR processor having some issues with the import of the taxonomy annotations. It might also be that SIGNOR is restricted to humans, in that case it might be helpful to indicate that in the statements, if possible?

Thanks a lot in advance!

**Comment by bgyori** [comment]
Right, so this PR introduced a number of validation features and fixed a bunch of bugs in input sources including Signor for similar kinds of invalid identifiers like the -1 above: https://github.com/sorgerlab/indra/pull/1172. If you want to produce all Signor statements in their latest form, you could try doing:
```python
from indra.sources import signor
from indra.statements import stmts_to_json_file
sp = signor.process_from_web()
stmts_to_json_file(sp.statements, 'signor_indra_stmts.json')
```

**Comment by helena-balabin** [comment]
Okay, that's good to know. For now we've decided to just filter out these statements, but I'll definitely try out your solution if I decide to include them again. Thanks!
