### ISSUE TITLE
dialogue.bio generates Internal Server Error

### ISSUE THREAD

**Issue by djinnome** [sorgerlab/indra#1316]
Hi folks,

We went to dialogue.bio and both Clic and SBGNViz  resulted in the same error:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by djinnome** [comment]
In the past, when I had troubling using dialogue.bio, it was because I was on VPN, but I was not on VPN this time

**Comment by bgyori** [comment]
Thanks, I can see the error in the logs and will investigate/fix it.

**Comment by bgyori** [comment]
Done, for whatever reason MongoDB stopped working on the server and had to be reinstalled, I was able to start a session now. Let me know if you run into any other issues!
