### ISSUE TITLE
Strange entries (multiple gene names, semicolons) in Uniprot entries file

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#133]
Here's an odd one I came across:

```
In [1]: from indra.databases import uniprot_client

In [2]: uniprot_client.get_gene_name('P84052')
Out[2]: 'His2A; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; '
```
It turns out that this is actually the entry in the uniprot_entries.tsv file, and there's a few others like it. Here are lines 278787-278802 in the uniprot_entries.tsv file:

```
P84040	His4; His4r; His4:CG31611; His4:CG33869; His4:CG33871; His4:CG33873; His4:CG33875; His4:CG33877; His4:CG33879; His4:CG33881; His4:CG33883; His4:CG33885; His4:CG33887; His4:CG33889; His4:CG33891; His4:CG33893; His4:CG33895; His4:CG33897; His4:CG33899; His4:CG33901; His4:CG33903; His4:CG33905; His4:CG33907; His4:CG33909	7227	H4_DROME
P84041	His4; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; 	7220	H4_DROER
P84042	His4; His4r	7224	H4_DROHY
P84043	His4; ; ; ; ; ; ; ; ; ; ; ; 	7240	H4_DROSI
P84044	His4; ; 	7245	H4_DROYA
P84045	His4	6832	H4_TIGCA
P84046	His4	7155	H4_CHITH
P84047	His4	92525	H4_ASEAQ
P84048	His4	57686	H4_ACRAS
P84049	His4	34708	H4_MYRRU
P84050	His4	7186	H4_RHYAM
P84051	His2A; His2A:CG31618; His2A:CG33808; His2A:CG33814; His2A:CG33817; His2A:CG33820; His2A:CG33823; His2A:CG33826; His2A:CG33829; His2A:CG33832; His2A:CG33835; His2A:CG33838; His2A:CG33841; His2A:CG33844; His2A:CG33847; His2A:CG33850; His2A:CG33862; His2A:CG33865	7227	H2A_DROME
P84052	His2A; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; 	7220	H2A_DROER
P84053	His2A	7224	H2A_DROHY
P84054	His2A; ; ; ; ; ; ; ; ; ; ; ; 	7240	H2A_DROSI
P84055	His2A; ; 	7245	H2A_DROYA
```

The common denominator here appears to be fields with many gene names separated by semicolons. Most likely these represent the many gene names associated with histone proteins. Not sure if this is unique to the Drosophila entries or what.

**Comment by bgyori** [comment]
This is how it comes back from UniProt. I am only collecting the "Primary" gene names for each UniProt entry so these are cases where one protein product corresponds to multiple genes. There are a bunch of human examples like:
http://www.uniprot.org/uniprot/P81534#gene_name_table
http://www.uniprot.org/uniprot/Q30KQ2#gene_name_table
http://www.uniprot.org/uniprot/Q5VWM5#gene_name_table
I am defaulting to the first one in the list for now, unless there is a specific need for another solution. Changes in here: 59c15857ee8c6ce6d879627b0de65dfe18beef4e

**Comment by jmuhlich** [comment]
Worth reading here:

http://www.uniprot.org/help/redundancy

Specifically:

> When different genes in the same species give rise to the same protein sequence, they were merged in a single UniProtKB/Swiss-Prot record and the gene names listed in the gene name subsection. See for example the entry for human histone H3.1 ([P68431](http://www.uniprot.org/uniprot/P68431#names_and_taxonomy)). However, we tend to demerge many of these entries, and for newly annotated proteins, generate separate sequence entries in case of multiple genes coding for identical protein sequences, e.g. [P08409](http://www.uniprot.org/uniprot/?query=replaces:P08409).

Their phrasing "we tend to demerge many of these entries" is not particularly helpful though.
