### ISSUE TITLE
Add MGI client

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#1338]
While working on #1336, it would have been nice to have some MGI utilities. @bgyori mentioned to check the BEL processor, which says this:

https://github.com/sorgerlab/indra/blob/2ac6194b0d4f31a4c5ae627bdf3a548212a2eb00/indra/sources/bel/processor.py#L535-L542

Since i've already implemented this functionality in PyOBO, I think I can create some resources based on that in the `update_resources.py` file, then make a simple client to wrap them

**Comment by bgyori** [comment]
It's a bit confusing, I accidentally left the old comment there
```
 # For now, handle MGI/RGD but putting the name into the db_refs so 
 # it's clear what namespace the name belongs to 
 # FIXME: Full implementation would look up MGI/RGD identifiers from 
 # the names, and obtain corresponding Uniprot IDs 
```
but what is written in FIXME is precisely what is implemented now.
