### ISSUE TITLE
Found unstandardized references while building DUB portal

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#1350]
Looks like there is a problem with standardizing ChEBI identifiers floating around somewhere:

```
INFO: [2021-11-10 14:13:56] indra.assemblers.html.assembler - Removing CHEBI from refs due to too many matches: {'CHEBI:131902', '131902'}              
```

**Comment by bgyori** [comment]
Those come from the DB, we would have to include post-processing in the given application to clean those up.

**Comment by bgyori** [comment]
Thanks, these have been fixed over time in INDRA and the `indra.tools.fix_invalidities`(https://indra.readthedocs.io/en/latest/modules/tools/index.html#module-indra.tools.fix_invalidities) module allows post-processing in cases where previously generated and saved statements have to be fixed up.
