### ISSUE TITLE
Request reach module has some problem

### ISSUE THREAD

**Issue by lyfer233** [sorgerlab/indra#1353]
I use pip install indra, then I try these code 
```py
from indra.sources import reach
rp = reach.process_text('The effects of PTK787, a PDGFR and vascular-endothelial growth factor receptor (VEGFR) inhibitor')
```
I find the response from reach always 400 code. So I think the interface about the send text to reach and received response have some problems. 
To ensure the reach server lead to this problem, I have try write code directly request reach interface in local. And my code as these
```python
url = r"http://agathon.sista.arizona.edu:8080/odinweb/api/text"
my_text = {
    "text": "MEK2 phosphorylates ERK1 at Thr-202 and Tyr-204",
    "output": "fries",
}
response = requests.post(url=url, data=my_text)
print(response.text)
```
it quickly and successful return the correct results.
So far, I choose to avoid use `process_text` function in directly, I'm write the code to request the reach and take result into `reach.api.process_json_str` function, then take my statement. 

My Computer env:
- Windows 11
- Python 3.6
- INDRA 1.21.0

**Comment by bgyori** [comment]
Hi @lyfer233, I couldn't reproduce this issue. For me,
```
from indra.sources import reach
rp = reach.process_text('The effects of PTK787, a PDGFR and vascular-endothelial growth factor receptor (VEGFR) inhibitor')
```
works correctly but returns no INDRA Statements, whereas
```
rp = reach.process_text('MEK2 phosphorylates ERK1 at Thr-202 and Tyr-204')
```
also works and returns two statements in the processor.

So I suspect the issue could be related to your local environment. Do you have the environmental variable `REACH_TEXT_URL` set to something? Or did you change the `REACH_TEXT_URL` entry in your INDRA config at `~/.confing/indra/config.ini` (or its Windows equivalent)?

**Comment by lyfer233** [comment]
OK, you're right. I try use other computer to process same code and success running. probably my env config have some problems. :joy:
