### ISSUE TITLE
HPRD is now behind login, server responds with 500

### ISSUE THREAD

**Issue by kkaris** [sorgerlab/indra#1421]
Although the files seem to not have been updated recently, they are now behind login (see https://hprd.org/download). Trying the direct [download URL](http://www.hprd.org/RELEASE9/HPRD_FLAT_FILES_041310.tar.gz) gives a server error (500 response).

**Comment by bgyori** [comment]
This is not an issue, at the level of INDRA since we don't have any API functions that assume downloading from the web is possible. The API functions assume local files which haven't changed and would still work.
