### ISSUE TITLE
RLIMS-P invalid statement error

### ISSUE THREAD

**Issue by kkaris** [sorgerlab/indra#1422]
Running the processor on the latest available data (see https://hershey.dbi.udel.edu/textmining/export/), there are two errors when processing the medline file and they are both about the `idString` in [the `id_dict` when getting agents](https://github.com/sorgerlab/indra/blob/master/indra/sources/rlimsp/processor.py#L211) containing a badly formatted identifier, both of the form `<identifier>;<decimal>'`, and in both cases MESH identifiers.

Right now the error occurs first at the stage where the statements are [checked in the processor](https://github.com/sorgerlab/indra/blob/master/indra/sources/rlimsp/processor.py#L30) with `assert_valid_statements`.

Suggestions:
- Leave the statement extraction as is, but change to check individual statements with `assert_valid_statement` and skip the invalid statements.
- Add a check for semi-colons in where [MESH is handled](https://github.com/sorgerlab/indra/blob/master/indra/sources/rlimsp/processor.py#L253) and split on it if present.

**Comment by bgyori** [comment]
I fixed this in the processor

**Comment by kkaris** [comment]
Resolved by #1423
