### ISSUE TITLE
cBioPortal legacy API is shut down

### ISSUE THREAD

**Issue by kkaris** [sorgerlab/indra#1434]
It looks like cBioPortal has shut down their legacy API at http://www.cbioportal.org/webservice.do that we use in the cbio client.

There are alternatives documented at https://docs.cbioportal.org/web-api-and-clients/, one is to use their new rest API: https://www.cbioportal.org/api/swagger-ui/index.html another is to use the Python client: https://docs.cbioportal.org/web-api-and-clients/#python-client

**Comment by bgyori** [comment]
I started implementing a new client on a branch, the endpoints and nomenclature has changed a lot so each functionality needs to be investigated to figure out how to reproduce.

**Comment by bgyori** [comment]
Done in #1435
