### ISSUE TITLE
RasGef should be considered "refinement" of Activation

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#144]
```RasGef(sos, 'activity', ras)``` and ```Activation(sos, 'activity', ras, 'gtpbound')``` represent the same mechanism except that the RasGef one is actually more specific because it adds specific biochemical semantics to the activation reaction. Right now these two statements are treated as completely independent, which leads to potential duplication in assembled models. 

In addition, given three statements like ```RasGef(sos1, 'activity', kras)``` and ```Activation(sos1, 'activity', hras, 'activity'), Activation(sos2, 'activity', kras, 'activity')``` the Mechanism linker should be enhanced to identify that 
* sos1 has RasGef activity, suggesting that the activation of hras might be mediated by gef-like activity (perhaps add a gef_activity type??);
* kras has gtpbound activity, suggesting that the activation by sos2 activates kras's gtpbound activity.

Similar relationships would apply for RasGap and negative Activation.

**Comment by bgyori** [comment]
What does BEL use as an activity type for SOS? Is there one called `rasgef? If not, should we introduce one?
