### ISSUE TITLE
Access Biopax

### ISSUE THREAD

**Issue by Siliegia** [sorgerlab/indra#1444]
I suddenly can not retrieve biopax statements with INDRA. Just running the code from the documentation results in an error message:

```
from indra.tools.gene_network import GeneNetwork
gn = GeneNetwork(['H2AX'])
biopax_stmts = gn.get_biopax_stmts()

ConnectionError: ('Connection aborted.', BadStatusLine('\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00ÿÿÿ\x00\x00\x04\x08\x00\x00\x00\x00\x00\x7fÿ\x00\x00\x00\x00\x08\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01')) 
```

**Comment by bgyori** [comment]
Hi @Siliegia, this is due to the fact that the Pathway Commons web service switched from http to https. This requires updating the client that calls Pathway Commons by doing
```
pip install -U pybiopax
```
to get its latest version. Please let me know if that works!

**Comment by stephanmg** [comment]
@bgyori thanks, this fixed it for me.
