### ISSUE TITLE
Need to unpack BEL protein family statements into the relevant family members

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#15]
In parsing statements in the BEL large corpus, we frequently find statements involving protein families, e.g. "AKT_FAMILY". Currently these enter the model as monomers named by the family. Instead, we should locate the mapping between the family and its specific members (and their HGNC names) and replace the statements involving families with all of the relevant family members.

**Comment by bgyori** [comment]
We have this resource to help with this:
http://resource.belframework.org/belframework/1.0/resource/protein-families.bel
And we should do the same for named complexes:
http://resource.belframework.org/belframework/1.0/resource/named-complexes.bel

**Comment by johnbachman** [comment]
This was handled by the creation of the hierarchy system, named families in the bioentities repository, and the mapping of BEL family names and members into the bioentities hierarchy.
