### ISSUE TITLE
Update the grounding mapper to use the ignore.csv file from Bioentities

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#157]
...rather than looking for Nones in the grounding map. In fact, the grounding map should now never contain Nones as targets of texts, and the check_references.py script should reflect that.

**Comment by bgyori** [comment]
Wow, this hasn't been done yet...?

**Comment by johnbachman** [comment]
I know, I was expecting the code elves to have taken care of this one already :)

**Comment by johnbachman** [comment]
Maybe self-patching software should be the next big DARPA project :)

**Comment by johnbachman** [comment]
Correction! You are right, this is handled by the merging of the two files in load_grounding_map.
