### ISSUE TITLE
Multiple rounds of hierarchy building on import

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#158]
We currently get 3 rounds of this logging message:

```INFO: indra/hierarchy_manager - Generating reverse lookup table for families```

**Comment by bgyori** [comment]
Well, one simple solution to make this go away is to remove the logging message! I don't think it's that important.

**Comment by johnbachman** [comment]
I suppose. I guess there is not too much overhead is involved in the family expansion, but might be worth checking.

**Comment by bgyori** [comment]
I can't believe I just noticed now but this is trivial... we have multiple hierarchies and each one generates a logging message. Removed in 336e139fcba4f74e907418470d3806aede006f18
