### ISSUE TITLE
Need to aggregate/infer information about site modifications during assembly

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#16]
Consider the sentences:

"XXX results in phosphorylation of EGFR and tyrosine 1068 and tyrosine 1172."
"GRB2 binds EGFR phosphorylated at residue 1068."

In parsing the second sentence about GRB2, a site name is ultimately required for the modification being referred to as a precondition for the binding event. However, it is not explicitly specified in that sentence that that residue is a tyrosine, thus, while the first statement will result in a Phosphorylation sentence that leads to specification of a site with name "Y1068" on EGFR, the second statement will not have sufficient information to identify the name of the appropriate site.

This points to the need to have a aggregation/inference step at assembly time for these issues to be resolved. If we have information anywhere about what the residue at 1068 is, then we use it in all references to that site.

Similarly, we may see the statement "GRB2 binds phosphorylated EGFR." Again, at assembly time the binding statement should key this back to the appropriate site modifications. This one is more advanced because the assembly process would need to identify the issue that it is unresolved whether phospho 1068 or 1172 is sufficient, or both must be phosphorylated.

**Comment by bgyori** [comment]
I think this is handled by the Preassembler. The way we conceptualize this problem has changed somewhat though. I'll close this for now.
