### ISSUE TITLE
Statements with non-equal matches_key should never be refinements of each other

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#164]
Example: assume all the details of bound agents are generated into the matches key but that refinement_of doesn't take into account details of bound agents. This results in a case where two statements won't be determined to be duplicate (since matches keys are different) but they will be refinements of each other (since equal statements are refinements of each other). This results in cycles in the supports/supported by graph. Thankfully the new networkx based BeliefEngine detects these cycles and throws an error. I am now fixing the second bug fitting this pattern and there could be more.

**Comment by johnbachman** [comment]
Aha! I saw the cycles thing several times when assembling large sets of statements, was wondering where that was coming from.

**Comment by bgyori** [comment]
So if that happens, jump into debug and do:
```
import networkx
cyc = networkx.find_cycle(g)
st1 = cyc[0]
st2 = cyc[1]
```
Here you have the matches_key of two statements st1 and st2 that are refinements of each other and that lets you retrace the bug.
