### ISSUE TITLE
Model annotations

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#18]
We keep track of evidence at the level of Statements but the generated model itself is not annotated. We could annotate each PySB rule by, for instance, the natural language sentence, the BioPax reaction, or the BEL statement that it was processed from.

**Comment by johnbachman** [comment]
Good point. This should be fairly straightforward. Also, does the BaseAgent
currently retain the HGNC/Uniprot ID? We could annotate the Monomers that
way.

**Comment by bgyori** [comment]
Monomers are annotated as of 443061a82f2a9030456ddf71d9db61a21ccd7eb1 but we still haven't done this for Rules.

**Comment by bgyori** [comment]
@johnbachman  would it make sense to add annotations that would refer back to INDRA Statements or evidence text/source in the PySB model?

**Comment by bgyori** [comment]
Added source statement UUID Annotation in d2aa7091836cb09b041e7770daa715dc58cfb0bb
