### ISSUE TITLE
Python 2/3 compatibility logging message

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#188]
This is displayed when importing certain modules of INDRA. The messages are related to the Python 2/3 compatibility imports. Can these be suppressed somehow?
```
INFO: indra/root - Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
INFO: indra/root - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
```

**Comment by johnbachman** [comment]
Do we use lib2to3 in INDRA? I think that's used in PySB, but I don't recall using it in INDRA.

**Comment by bgyori** [comment]
You might be right - they only display when I import the PysbAssembler.

**Comment by jmuhlich** [comment]
The problem is in networkx. They import lib2to3 to do some weird thing 
for parsing/writing some graph format, even though lib2to3 is meant to 
be an offline tool for transforming python source code. Looks like you 
need to add lib2to3 to the explicit list of logging levels in 
indra/__init__.py .

**Comment by jmuhlich** [comment]
BTW, even though sif_assembler is the module that imports networkx, 
indra.assemblers tries to import all assemblers. Thus the import of any 
assembler at all should trigger those lib2to3 log messages.

**Comment by bgyori** [comment]
Done in 016a96e8eb91894ee01aa329dcf0a22a2e79bad1. Thanks @jmuhlich !
