### ISSUE TITLE
Handle RegulateActivity statements in biopax processor

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#21]
There appear to be many reactions in BioPax of the form

```
From: MEK()
Catalyzed by: Raf(Active state,R)
To: MEK(Active state,R)
```

i.e., an ActivityActivity statement involving Raf and Mek. We should be able to process these in BioPax as we do for BEL.

The ActivityActivity statements may prove to be particularly useful when assembling them alongside other statements where the identity of the modifying enzyme is actually not clear, for example when the reaction is catalyzed by a complex (e.g., 14-3-3 % BRAF % KSR).

**Comment by bgyori** [comment]
This has been implemented a long time ago.
