### ISSUE TITLE
'Connection reset by peer' when using bel.process_ndex_neighborhood

### ISSUE THREAD

**Issue by FFroehlich** [sorgerlab/indra#220]
Hey,

For me the following script 

```
import indra
from indra import bel
bp = bel.process_ndex_neighborhood([ 'BRAF'])
```

always fails with the error `requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))`

Do I require any specific API key (or any other requirement) to use the openBEL resource?

**Comment by bgyori** [comment]
Hi, I believe this is a temporary issue with the web service which provides a query API to the BEL Large Corpus (bel2rdf.bigmech.ndexbio.org). We can follow up on this and I'll post here once it's fixed.

**Comment by bgyori** [comment]
Looks like the web service is back up and process_ndex_neighborhood is working.
