### ISSUE TITLE
setup biopax processer

### ISSUE THREAD

**Issue by FFroehlich** [sorgerlab/indra#250]
In order to use the biopax processer I had to install jnius and cython using `pip install` and set an appropriate value for `JAVA_HOME`. All these things should probably be done in `setup.py`. Under OSX the correct path to `JAVA_HOME` can be set via `export JAVA_HOME=$(/usr/libexec/java_home)`.

**Comment by bgyori** [comment]
Thanks for the comment - while I'm not claiming that it's impossible to do what you suggest, we've tried before and couldn't fully solve it this way. 

One issue is that Cython needs to be installed _before_ jnius is installed with two separate, sequential calls to pip install. They can't be included in the same list of pip installable packages. We also wanted to keep jnius optional to make sure the core of INDRA can be used without having to go through the rather complicated Java setup first.

JAVA_HOME can, indeed be exported in setup.py but that is not "permanent". JAVA_HOME needs to be set whenever java classes are to be used (not just at installation time), so it actually needs to go into one's profile or needs to be exported manually each time in a new terminal where jnius is used. I realize the documentation doesn't explicitly suggest putting the export in one's profile, I will add this. 

In terms of the `/usr/libexec/java_home` shortcut, I think that's a great idea in principle, my only concern is cases where someone has multiple versions of Java installed, including older versions (1.6, 1.7) or possibly newer versions, and it's not clear that `/usr/libexec/java_home` will point to a correct, working Java version by default. This is again something that has happened before and setting the path to a given version explicitly solved the problem. 

In any case, I'll look into this issue again and see if there's anything that can be simplified.

**Comment by FFroehlich** [comment]
Ah okay, that makes sense. I just realised that there is a detailed description on how to set up the biopax processor in the installation guide and I just forgot about that part after running into problems with the BEL processor.
