### ISSUE TITLE
OSX Installation

### ISSUE THREAD

**Issue by cannin** [sorgerlab/indra#256]
In addition to the JAVA_HOME variable I also had to enable JNI to make Indra work. Instructions are on this issue.  

https://github.com/kivy/pyjnius/issues/277

It might be good to include in the installation instructions. I'm on OSX 10.12.4.

**Comment by bgyori** [comment]
Thanks, that's a useful tip. Did you install "Legacy Java for OSX" (https://support.apple.com/kb/DL1572?locale=en_US) before trying this JNI setting? I'm wondering if the JNI setting you quote here is an _alternative_ to installing Legacy Java or whether it's an additional requirement.

**Comment by cannin** [comment]
I received the popup to install Legacy Java. I tried and then the installer complained I already had it. Maybe if you do not have the Legacy Java that is sufficient, but if you do then this extra step is necessary? In the instructions, I would say try Legacy Java first and if you still have issues then try this solution.

**Comment by bgyori** [comment]
Okay, I extended the instructions with this in 8c29044e007ccc4dcae90469faf03031a034c0ed. Once we have a better understanding of when this is needed I might refine the description in there.
