### ISSUE TITLE
BioPAX Processor should keep track of source database

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#257]
We currently propagate PathwayCommons UID-s for the source of each Statement, which is good, but it would be useful to explicitly propagate the source database (pid, psp, panther, etc.) too.

**Comment by johnbachman** [comment]
Whoops, closed by accident.

**Comment by johnbachman** [comment]
Maybe we should include this in annotations, as, say, "pc_source_db"?

**Comment by bgyori** [comment]
I think of it as part of a larger effort to allow the Belief Engine to look at multiple levels under the main source API. Like reach / rule_123, biopax / psp, etc. So some standardized annotation that works across sources might be better, if possible.

**Comment by bgyori** [comment]
Done in c6265f659d3a92fee0c2514880d553f08d500c88
