### ISSUE TITLE
Newstr in Python 2 pickles can cause error in Python 3

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#259]
I ran into a case where a db_refs['UP'] entry was pickled in Python 2 as `newstr`, and it was then used as a dictionary key, but `newstr` is considered unhashable and so it errors.

**Comment by bgyori** [comment]
The problem is this line: https://github.com/sorgerlab/indra/blob/master/indra/biopax/processor.py#L1041

**Comment by johnbachman** [comment]
As a policy matter, this should be resolved by creating pickles in Python3 only, with reminders via the ```indra.util._require_python3``` module added in 88a3227a952386b13
