### ISSUE TITLE
Reach should not require jnius by default

### ISSUE THREAD

**Issue by pagreene** [sorgerlab/indra#270]
To be more portable, jnius should not need to be imported by default when trying to use reach, seeing as the online resource can be used without needing jnius.

**Comment by pagreene** [comment]
I think that perhaps it could be designed to try to import it, then upon failure, simply give a notice or warning that the reach can not be run locally as a result. Currently the import of reach simply fails if you don't have jnius.

**Comment by bgyori** [comment]
I can't verify right now but the way I implemented is for it to print something like "Offline reading not available" if jnius can't be imported. If that's not the case then something might have changed that  causes it to raise an actual error - this should be fixed.

**Comment by bgyori** [comment]
It's strange that you got an error since these lines: https://github.com/sorgerlab/indra/blob/master/indra/sources/reach/reach_api.py#L21-L29
should handle exactly the case you described, I'm not sure how the error slipped through.

**Comment by pagreene** [comment]
That is strange. It does seem to be working now, insofar as I can import reach. It is possible I misread the error as a failure to load reach. In any case, it is all good now. Or there was some strange glitch in my installation. (This was on orchestra, where I was installing everything locally). I know my environment variables were a mess.

Closing as there appears to be no issue.
