### ISSUE TITLE
Parsing Biopax reactions into Statements introduces errors in identity of enzyme/substrate

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#28]
Example::

In [16]: bp = biopax_api.process_pc_pathsfromto(['KSR1'], ['BRAF'])

In [17]: bp.get_phosphorylation()
/Users/johnbachman/Dropbox/1johndata/Knowledge File/Biology/Research/Big Mechanism/indra/indra/biopax/processor.py:164: UserWarning: Unknown modification type residue modification, inactive
  warnings.warn('Unknown modification type %s' % mf_type)

In [18]: bp.statements
Out[18]: 
[Phosphorylation(KSR1, BRAF, PhosphorylationSerine, 151, [Evidence(biopax, [], [], None)]),
 Phosphorylation(KSR1, BRAF, PhosphorylationSerine, 753, [Evidence(biopax, [], [], None)]),
 Phosphorylation(KSR1, BRAF, PhosphorylationSerine, 578, [Evidence(biopax, [], [], None)]),
 Phosphorylation(KSR1, BRAF, PhosphorylationSerine, 750, [Evidence(biopax, [], [], None)]),
 Phosphorylation(KSR1, BRAF, PhosphorylationThreonine, 401, [Evidence(biopax, [], [], None)])]

This makes it appear that KSR1 is the kinase involved in the phosphorylation. Is this because KSR1 appears as part of a complex on the left hand side but is not itself the kinase? Can we disambiguate which one is the kinase?

**Comment by bgyori** [comment]
Unfortunately, it seems like these are the actual reactions that appear in PathwayCommons. See the circled reactions below. One says that active KSR1 activates BRAF (left), the other one says that active KSR1 phosphorylates multiple sites and activates BRAF (right). Based on what is in the database, I don't know of any way to distinguish this from a "real" kinase.

![ksr_braf](https://cloud.githubusercontent.com/assets/5939016/13034781/9fdf8610-d30c-11e5-9b96-882fe288ec57.png)

**Comment by johnbachman** [comment]
Incidentally, do the dotted lines on this graph indicate that the various YWHA* genes are members of the 14-3-3 family? Can we use that information somehow in our super/subfamily logic?

**Comment by johnbachman** [comment]
I've opened the more general issue #30 for tracking peculiar Biopax statements, so I'll close this one.
