### ISSUE TITLE
assemble_corpus.filter_gene_list should take into account Bioentities family members

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#286]
Currently if you have a mix of gene-level and family-level statements, calling filter_gene_list will remove all family-level statements, even though Bioentities allows us to determine that the family-level statement may be relevant to the genes in the gene list. These should be included in the filter, at least optionally.

**Comment by bgyori** [comment]
Yes that would be useful. The implementation is not that simple, actually, and should be refactored from here: https://github.com/sorgerlab/indra/blob/master/indra/tools/incremental_model.py#L200-L299

**Comment by johnbachman** [comment]
I didn't see your comment and I implemented as follows, taking as a cue the fact that filter_gene_list only operates on gene names, not grounding information:

```
    # If we're allowing families, make a list of all Bioentities IDs that
    # contain members of the gene list, and add them to the filter list
    filter_list = copy(gene_list)
    if allow_families:
        for hgnc_name in gene_list:
            gene_uri = hierarchies['entity'].get_uri('HGNC', hgnc_name)
            parents = hierarchies['entity'].get_parents(gene_uri)
            for par_uri in parents:
                ns, id = hierarchies['entity'].ns_id_from_uri(par_uri)
                filter_list.append(id)
```
...where ```ns_id_from_uri``` was refactored from expand_families into the hierarchy_manager to be symmetric with get_uri.

Of course, filter_gene_list should perhaps instead be refactored to operate on actual gene grounding information, in which case this should be redone to also look into Bioentities grounding information rather than agent names.

**Comment by johnbachman** [comment]
Incidentally we may want to do something similar for ```filter_enzyme_kinase``` (may file a separate issue for that)

**Comment by bgyori** [comment]
Oh I see, so here if you filter for "BRAF" and have "RAF" in statement, that would be retained. I realize that the implementation in IncrementalModel is more complicated because there, you have to filter by relationship to a prior model (i.e. a list of prior Statements) not a list of gene names. So yeah, I think in this filter, this simpler implementation would be good.

**Comment by johnbachman** [comment]
Yes and you raise an interesting point which is that even in the existing implementation, if there are Bioentities family or complex names that overlap with gene names, the Bioentities statements would already have been passed through! I think in most cases in Bioentities we now distinguish between these explicitly, e.g., "FOS_family" as the BE ID rather than just FOS, but it might be worth checking over these to see if/how this could happen.

**Comment by johnbachman** [comment]
Perhaps filter_gene_list should be renamed filter_name_list :)

**Comment by bgyori** [comment]
Yes, you could definitely rename that argument.

**Comment by bgyori** [comment]
Done in d7927d5ea334b35ebde80c00ea87833b9f676756
