### ISSUE TITLE
Context service returning 404 errors

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#291]
Error occurring in ```test_cx_assembler.test_set_context``` and ```test_context.test_get_mutations```. See Travis build 813.

**Comment by bgyori** [comment]
Worked for me earlier today, seems to be up and down constantly in the last few days. But this isn't really an INDRA issue though, is it?

**Comment by johnbachman** [comment]
Nope--though it manifests as one in the tests, obviously. Having it here just lets us track progress in resolving it.
