### ISSUE TITLE
HGNC client should have ability to identify genes by previous gene symbols

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#297]
This issue shows up when processing networks from NDEx, where nodes have names that represent gene symbols that may be outdated (and the network contains no other grounding information). I suspect that this may be an issue with other databases and machine-readable knowledge sources that were curated with gene names that are now out-of-date.

So the idea would be that if you call ```hgnc_client.get_hgnc_id(name)``` and the name represents a previously valid gene symbol (note: not an alias, that's probably too permissive) then it returns the current gene name for that symbol.

This is based on the assumption that previously valid gene symbols don't overlap with currently valid gene symbols, which may not be the case. If this is the case, then we should prefer the current gene symbol only.

**Comment by bgyori** [comment]
Yes, this is the issue I posted in #142, maybe we should implement something to solve it. This could be tricky because of the issue you point out: previous symbol being currently used for something else, but also, possibly, previous symbol having been replaced by multiple current symbols.
