### ISSUE TITLE
Make missing resource message in SiteMapper more informative

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#299]
When running the RAS Machine, I get the warnings:

```
INFO: indra/phosphosite - Could not load PhosphoSite data from file /Users/cthoyt/dev/indra/indra/databases/../resources/Phosphorylation_site_dataset.tsv
INFO: indra/phosphosite - Source Exception: [Errno 2] No such file or directory: '/Users/cthoyt/dev/indra/indra/databases/../resources/Phosphorylation_site_dataset.tsv'
```

I'm not exactly sure what this resource is or how it's produced, so it would be nice to update the documentation accordingly. It looks like the `indra.databases.phosphosite_client` tries to load it up and fails since it's not stored in the repository explicitly, like many of the other resources that are stored in `indra.resources`.

**Comment by bgyori** [comment]
Hey, so these have nothing to do with the RAS Machine and are completely benign. They come from the indra.preassembler.site_mapper module, where this error message can be made more informative.

**Comment by bgyori** [comment]
Also, this should probably just be solved via #280

**Comment by johnbachman** [comment]
The terms of the Phosphosite data prevents redistribution, which is why we can't include it in the repo. The SiteMapper will work without the Phosphosite data, but it works better when we have it. Hence the INFO message.

**Comment by cthoyt** [comment]
Aha! That makes sense. It looks like it's not a hassle to get rights to download the Phosphosite data, so maybe the solution to my issue would be to provide a script that downloads and reformats the files to the format that INDRA uses

**Comment by johnbachman** [comment]
Where do we stand on this? As I recall getting a copy of the PhosphoSite data requires filling out a request form and waiting for CST to get back to you. Is there now a direct download available?

**Comment by cthoyt** [comment]
Okay so their site was a bit misleading - there are download links but when you click them it asks you to get an account. I'll report on the rest of the process.

Even if the data is behind a username/password, it might still be possible to automate download, parsing, and reformatting. I will report after I get the rights

**Comment by johnbachman** [comment]
Can I close this then?

**Comment by cthoyt** [comment]
I guess I had my blinders on - there was a direct link for the file I needed within a list of other stuff that INDRA doesn't use. Sorry for the confusion

**Comment by cthoyt** [comment]
I found that the download location can be accessed programatically from https://www.phosphosite.org/downloads/Phosphorylation_site_dataset.gz in case you want to provide a mechanism to download automatically (technically this isn't the same as distributing it yourself)

**Comment by johnbachman** [comment]
Good idea, thanks!
