### ISSUE TITLE
Example of conversion from BioPAX to PyBEL

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#323]
Now that the PyBEL exporter is (mostly) done, it would be nice to add an example of converting a BioPAX document to PyBEL in either the models folder, or the documentation.

**Comment by johnbachman** [comment]
Hi @cthoyt, I tried the following simple example:

```
import pybel
import requests
from indra.tools import assemble_corpus as ac
from indra.sources import biopax
from indra.assemblers import PybelAssembler

bp = biopax.process_pc_pathsbetween(['BRAF', 'MAP2K1'])
stmts = ac.map_sequence(bp.statements)
stmts = ac.run_preassembly(stmts)
pba = PybelAssembler(stmts, name='INDRA Biopax to PyBEL test',
                     description='Test of converting a simple biopax model '
                                 'to PyBEL using INDRA.',
                     version='0.0.2')
pba.make_model()
# Upload to PyBEL web
url = 'https://pybel.scai.fraunhofer.de/api/receive'
headers = {'content-type': 'application/json'}
requests.post(url, json=pybel.to_json(pba.model), headers=headers)
```

Model seems OK, has 25 nodes, but I get an undefined error when I try to view on PyBEL web (http://pybel.scai.fraunhofer.de/explore/query/403)--any idea what the issue is?

**Comment by cthoyt** [comment]
That's really wonderful! I think that it's really been a long time coming to see a script that turns BioPAX into BEL :)

Is there a way to import an entire BioPAX document, or does this only work by using a query interface to Pathway Commons?

Unfortunately, I was unable to reproduce your error. http://pybel.scai.fraunhofer.de/explore/query/403 is working fine for me. It might have been because I haven't deployed a new, shiny, multithreaded version of PyBEL Web, and someone else was using it at the same time as you

**Comment by bgyori** [comment]
Yes, `biopax.process_owl` lets you process and BioPAX OWL file. It can be very slow for large files though.

**Comment by cthoyt** [comment]
I'm happy with this, and added these examples to the PyBEL documentation as well. Thanks!
