### ISSUE TITLE
Test database sometimes can't be reached.

### ISSUE THREAD

**Issue by pagreene** [sorgerlab/indra#333]
For some reason, when running tests or otherwise trying to connect to the test database, a connection cannot be establish. This is a very intermittent error for users, but is a consistent issue for Travis, so that the database features are currently not tested on Travis.

**Comment by cthoyt** [comment]
The first ~30 lines from the Travis configuration in PyBEL might be a good example how to include database tests in your suite: https://github.com/pybel/pybel/blob/develop/.travis.yml

**Comment by bgyori** [comment]
I don't think this is an issue anymore
