### ISSUE TITLE
Hierarchy for activity types

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#34]
Might be worthwhile having a hierarchy of activity types so that statements involving activities at various levels of resolution could also be subject to refinements.

For example, the statement 'X increases the kinase activity of Y' should be a refinement of 'X increases the activity of Y'.

Not sure how important this will be in practice--it's not clear how often the distinctions will be made in database entries or text.

**Comment by bgyori** [comment]
There is also a more fundamental issue: standardizing the strings that are passed as activity types. This is inconsistent now across input sources.

**Comment by bgyori** [comment]
Done in 9394ae62a7f9823446e7c825c53d3e2b13ea4cc7
