### ISSUE TITLE
Add tests for BEL script and Node-Link JSON processing

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#358]
These API calls are not directly tested yet as of PR #356.

**Comment by bgyori** [comment]
@kkaris since you just worked on #826, could you add a test to test_pybel_api.py for reading a small Node-Link JSON file (similar to the `test_process_jgif`)? We already have a test for BEL Script reading in test_bel.py so no need to add that.

**Comment by kkaris** [comment]
Resolved in #832
