### ISSUE TITLE
Find a way to use Reach/Eidos jars simultaneously

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#394]
Currently the fat jars for Reach and Eidos can't simultaneously be on the CLASSPATH because they pack conflicting dependencies that lead to errors. This has prevented me from adding tests for Eidos without breaking Travis builds. A solution would be to introduce REACHPATH and EIDOSPATH variables that are added to the CLASSPATH from within the respective APIs to make sure the right one is on the CLASSPATH at the right time.

**Comment by jmuhlich** [comment]
I think you can use separate explicit class loaders in Java to manage this, rather than using the default class loader.

https://stackoverflow.com/a/6108133
https://en.wikipedia.org/wiki/Java_Classloader#JAR_hell

**Comment by bgyori** [comment]
That stackoverflow suggestion is good but that piece of code would have to be integrated into pyjnius to work (since pyjnius is the one that actually ends up loading a class you specify). I'll have to dig into it a bit more.

**Comment by bgyori** [comment]
The issue is that as soon as `autoclass` is imported, the Java VM is started (which reads the CLASSPATH in whatever state it is in when `autoclass` loads) and it's not possible to effectively change the CLASSPATH afterwards to use JARs that weren't initially on it. This is also discussed in https://github.com/kivy/pyjnius/issues/316, and there doesn't seem to be a solution yet.

**Comment by ctrueden** [comment]
> it's not possible to effectively change the CLASSPATH afterwards to use JARs that weren't initially on it.

If all you want is to add JARs to the classpath of a running Java, apparently that is possible; see https://github.com/kivy/pyjnius/issues/434#issuecomment-515693635. Not sure if changes would be needed on the pyjnius side, though.

**Comment by bgyori** [comment]
Thanks, @ctrueden, I guess the issue is that I would need to both add _and remove_ paths from the CLASSPATH during runtime (see https://github.com/kivy/pyjnius/issues/411#issuecomment-540463639) to solve this issue.

**Comment by ctrueden** [comment]
@bgyori Ah, yeah, in that case you'd need to use custom class loaders on the Java side. And you can't wrap those dynamically loaded classes on the Python side (see kivy/pyjnius#316); if you try you'll see something like:
```
Traceback (most recent call last):
  File "jnius/jnius_export_class.pxi", line 766, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 845, in jnius.JavaMethod.call_method
  File "jnius/jnius_conversion.pxi", line 212, in jnius.convert_jobject_to_python
  File ".../jnius/reflect.py", line 159, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
jnius.JavaException: Class not found b'my/package/MyClass'
```
But you _can_ work with dynamically loaded classes on the Java side... as long as they don't leak to Python as return values or whatnot.
