### ISSUE TITLE
Eidos update breaks INDRA-Eidos API

### ISSUE THREAD

**Issue by adarshp** [sorgerlab/indra#396]
Recent updates to Eidos have broken the functioning of the INDRA-Eidos API.

From looking at the changes in the codebase, the main culprit is the change in the type signature of the extractFrom function in EidosSystem.scala - it used to be String -> Vector[Mention], but is now String -> AnnotatedDocument (which shows up in org/clulab/wm/serialization/json/JLDSerializer.scala). Any idea how to fix this?

**Comment by bgyori** [comment]
Thanks, will work on this tomorrow!

**Comment by adarshp** [comment]
I think I fixed it - just submitted a PR.
