### ISSUE TITLE
test_preassembler.test_combine_duplicates sometimes fails

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#40]
When running the tests repeatedly, this line `assert(pa.unique_stmts[0] == p5) # MEK phos ERK`
sometimes fails and other times doesn't.

**Comment by bgyori** [comment]
Looks like this is fixed as of 89d9fb7801236e719988526e4c3faa9ea55f0edb

**Comment by bgyori** [comment]
Reopening because this happened again.

**Comment by johnbachman** [comment]
Should have been fixed by 17160fd93.
