### ISSUE TITLE
Import reach does not work 

### ISSUE THREAD

**Issue by ivanovaos** [sorgerlab/indra#416]
Hi all, 
Thanks for this nice tool. I have installed it using the guideline from the website (pip install git+https://github.com/sorgerlab/indra.git). I tried to use the pmid parser, but got an error. I am on Mac Os X 10.12.6, python 3.6. Right after installation, there was an error message that "reach_rule_regexps.txt" could not be found, I downloaded it manually. Then another error message appeared.

>>> from indra.sources import reach
ERROR: [2018-03-08 13:13:59] indra/reach - Could not import jnius, offline reading cannot be used.

I then installed Cython and jnius with pip, but it didn't help.

**Comment by bgyori** [comment]
Hello, despite that message, you can use INDRA's interface to the REACH _web service_ to for reading. For instance,
```
from indra.sources import reach
reach.process_text('JAK1 activates STAT3.')
```
The error is only relevant if you would like to use a _local_ copy of the REACH system. As the message message suggests, you need to have the `jnius` package and its dependencies installed. See detailed instructions here: http://indra.readthedocs.io/en/latest/installation.html#pyjnius

If using REACH locally is your goal, you can either build REACH yourself (https://github.com/clulab/reach), or download a JAR of it from here: http://sorger.med.harvard.edu/data/bachman/reach-82631d-biores-e9ee36.jar

Let me know if this helps!

**Comment by ivanovaos** [comment]
Thanks for your fast reply, @bgyori 
I have also tried to use the line you suggested and the example from the indra website. I have got this Error: 
>>> reach_processor = reach.process_pmc('3717945')
ERROR: [2018-03-08 13:41:27] indra/reach - Could not connect to REACH service:
ERROR: [2018-03-08 13:41:27] indra/reach - HTTPConnectionPool(host='agathon.sista.arizona.edu', port=8080): Max retries exceeded with url: /odinweb/api/nxml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113d44fd0>: Failed to establish a new connection: [Errno 60] Operation timed out',)

Probably, it is because I am behind proxy?

**Comment by bgyori** [comment]
Just tried it and that same call worked for me, though it took 2-3 minutes to return with a result for this full-text paper. In the end, `reach_processor.statements` contained 174 INDRA Statements. It's possible that you have a proxy which is causing problems with the connection. Could you try reading something small like my example `reach.process_text('JAK1 activates STAT3.')`, which should give you a result almost immediately and see if it works?

**Comment by bgyori** [comment]
@ivanovaos did things work out in the end? Let me know if you are still having an INDRA-related issue, otherwise I'll close this.

**Comment by ivanovaos** [comment]
@bgyori thank you, I indeed tried it from home (without proxy) and it worked! Still figuring out how to play with the information, but this issue can be closed.

**Comment by bgyori** [comment]
Great, thanks!
