### ISSUE TITLE
Add end-to-end WM test for Eidos JSON-LD output

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#425]
We should have an end-to-end test where we fetch this JSON: https://raw.githubusercontent.com/clulab/eidos/master/example_output/example_mar6.jsonld, process it and assemble it into various models to make sure things are operational.

**Comment by bgyori** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add end-to-end (Eidos -> CAG) test for https://raw.githubusercontent.com/clulab/eidos/master/example_output/example_mar6.jsonld](https://trello.com/c/dBsgtMeS/59-add-end-to-end-eidos-cag-test-for-https-rawgithubusercontentcom-clulab-eidos-master-exampleoutput-examplemar6jsonld)

**Comment by pagreene** [comment]
Addressed by https://github.com/sorgerlab/indra/pull/427
