### ISSUE TITLE
Phosphorylation sites for different protein isoforms

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#45]
I get the following phosphorylation statements from Pathway Commons:

```
 Phosphorylation(EGFR(), SHC1(), PhosphorylationTyrosine, 194),
 Phosphorylation(EGFR(), SHC1(), PhosphorylationTyrosine, 195),
 Phosphorylation(EGFR(), SHC1(), PhosphorylationTyrosine, 272),
 Phosphorylation(EGFR(), SHC3(), PhosphorylationTyrosine, 218),
 Phosphorylation(EGFR(), SHC3(), PhosphorylationTyrosine, 219),
 Phosphorylation(EGFR(), SHC3(), PhosphorylationTyrosine, 256),
 Phosphorylation(EGFR(), SHC3(), PhosphorylationTyrosine, 257),
 Phosphorylation(EGFR(), SHC3(), PhosphorylationTyrosine, 283),
 Phosphorylation(EGFR(), SHC3(), PhosphorylationTyrosine, 301)]
```

These all raise errors against the Uniprot reference sequence. However, for SHC3, there is another isoform, the "p52" isoform, with a difference upstream sequence:

http://www.uniprot.org/uniprot/Q92529#sequences

In phosphosite it's clear that all of the tyrosines mentioned are correct for this isoform:

http://www.phosphosite.org/proteinAction.action?id=4936&showAllSites=true (click "show isoforms" in the chart below).

The same is true for SHC1, but this time it's isoform p46:

http://www.uniprot.org/uniprot/P29353#sequences

I also found the same to thing for RPS6KB1, where the T389 listed in Pathway Commons is correct, but for the "Isoform Alpha 2" which is missing the first 23 amino acids.

Is it possible that Pathway Commons has information on the isoforms involved in the statements and we are not extracting it?

If not, we could write check_statements to not only determine if the sequence is not a match, but also to see if it is a match for a different isoform of the protein.

**Comment by bgyori** [comment]
PathwayCommons, unfortunately, doesn't give us this information. I think the site mapper is the best solution we have so far and though there is some manual curation involved, it solves this problem. Closing for now.
