### ISSUE TITLE
Add enhanced grounding mappers

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#454]
I was just running my own INDRA machine for APP-related research and when outputting with the PyBEL Assembler, got logging like this:

```
...
WARNING: [2018-03-28 12:54:32] indra/pybel_assembler - Agent fibrillary_Abeta() has no grounding.
...
WARNING: [2018-03-28 12:54:32] indra/pybel_assembler - Agent scavenger_receptors(activity) has no grounding.
...
WARNING: [2018-03-28 12:54:32] indra/pybel_assembler - Agent amyloid_beta() has no grounding.
...
WARNING: [2018-03-28 12:54:32] indra/pybel_assembler - Agent RAGE_receptors(activity) has no grounding.
...
WARNING: [2018-03-28 12:54:32] indra/pybel_assembler - Agent tau_proteins() has no grounding.
...
WARNING: [2018-03-28 12:54:32] indra/pybel_assembler - Agent APOE_epsilon4() has no grounding.
...
```

For the entities I've highlighted, I think I can generate mappings to elements in BEL. For example, amyloid beta can be mapped to a ChEBI term, or a bel term like `p(HGNC:APP, frag(673_711))` (I probably got the numbers wrong, but you can see the idea)

In general, a domain expert might be able to provide mappings. Might we develop a way to load a mapping file to help INDRA with cases like this?

**Comment by bgyori** [comment]
Yes, absolutely! The `indra.preassembler.grounding_mapper.GroundingMapper` class takes a grounding_map as an argument. We have a built-in one that's used by default but you can extend that or replace that for your own application. The only thing missing is that the interface which the machine uses (based on `indra.tools.assemble_corpus`) doesn't reveal this option at the API level, but that's easy to add.

**Comment by bgyori** [comment]
This is where we need to make it possible to use the non-default grounding map: https://github.com/sorgerlab/indra/blob/master/indra/tools/incremental_model.py#L109

By the way, INDRA's default grounding map is adopted from the FamPlex grounding map here: https://github.com/sorgerlab/famplex/blob/master/grounding_map.csv, so if you map any ungrounded strings that you feel are generally useful, you can PR your changes to FamPlex!
