### ISSUE TITLE
Move some things from util.aws into tools.reading.util

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#492]
The functions that are generic for AWS and can stay in `indra.util.aws` are:
- kill_all
- get_jobs
- get_job_log
- get_log_by_name
- dump logs
- get_indra_logs_by_priority

The rest could be moved into `indra.tools.reading.util`.

**Comment by pagreene** [comment]
I would add:
- tag_instance
- tag_myself
- get_batch_command
- run_in_batch

From my `fix_autoreading`.

**Comment by bgyori** [comment]
I see, I agree those could move in the other direction (i.e. currently in `indra.tools.reading` and could be moved into `indra.aws.util`.

**Comment by pagreene** [comment]
I made the change in my `fix_autoreading` branch.

**Comment by bgyori** [comment]
Fixed in #494
