### ISSUE TITLE
In CX assembler, links between agents in Complex statements should be undirected if possible

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#54]
Currently the links between agents are directed, presumably by the order of the agents in the Complex statement.

**Comment by bgyori** [comment]
I am aware of this - the CX documentation says edges  are always directed but applications using CX can use metadata to determine that an edge should in fact be undirected.

**Comment by bgyori** [comment]
From: http://www.ndexbio.org/data-model/
"edges are implicitly directed, but formats can choose annotations schemes to override this"

The same document has an example of an edgeAttribute

```
{
"n": "interaction",
"po": 84,
"v": "undirected"
},
```

but I tried this and NDEx doesn't make the edge undirected.

**Comment by bgyori** [comment]
This is handled in Cytoscape / NDEx visual styles, INDRA provides all the required information to do it as of 85af184e2cdfb7260099cc20ca085ea41aa57a49.
