### ISSUE TITLE
Complex statements appear to be extracted from BEL/Biopax without evidence objects

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#55]
An observation from the Ras 220 model. None of the Complex statements have evidence associated with them.

**Comment by bgyori** [comment]
BioPAX is fine, it extracts evidence for Complexes. Maybe you just didn't do get_complexes() on your query? However, the current way we extract Complexes from BEL makes it difficult to extract evidence. But I'll modify the graph query to do this.

**Comment by bgyori** [comment]
Fixed in 65458aef9528184a3940929c320b354341fc4d38
