### ISSUE TITLE
Helper function errors when running tests

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#595]
The file `make_raw_statement_test_set` should be renamed so that it doesn't contain `test` in its name to make sure that nosetests doesn't try to run it as if it were a test.
```
======================================================================
ERROR: indra.tests.make_raw_statement_test_set.make_test_statements
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: make_test_statements() missing 3 required positional arguments: 'a', 'b', and 'source_api'
```

**Comment by pagreene** [comment]
This is already fixed in the `get_statement_essentials` branch.

**Comment by bgyori** [comment]
It would be better to rename the file, not just the function since I think `make_raw_statement_test_set` is still being run in that file as if it were a test function (it just doesn't error).

**Comment by bgyori** [comment]
Great! I FF-ed get_statement_essentials and will merge it now.

**Comment by bgyori** [comment]
Done in #592
