### ISSUE TITLE
Move the 'TEXT' entry for agents in a statement from Agent.db_refs to Evidence

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#617]
Currently the raw text associated with an entity is stored in the Agent.db_refs['TEXT'] field, so information about the raw text for different sentences is lost when Statements are combined during preassembly. This information should be stored in the Evidence object representing the individual extractions. Since there are multiple Agents associated with the Statement, this means that the method of storing text info for the agent would have to be mapped backed to each, specific agent, potentially including BoundCondition agents.

**Comment by pagreene** [comment]
Interesting. Would we still want agents in the "TEXT" namespace for the database? Would we want to include all the variants for a preassembled statement?
