### ISSUE TITLE
Capture character positions for specific entities in the REACH processor

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#618]
Currently the REACH processor captures the raw text for extracted entities but not the sentence coordinates/position. It would be useful to propagate this information into the Statement via the Evidence.annotations dictionary so that downstream applications could potentially highlight the entities involved in the context of the original sentence. Relates to #617 in that this will also involve representing agent-specific information in the Evidence object.

**Comment by bgyori** [comment]
This was done in #684
