### ISSUE TITLE
EnglishAssembler does not distinguish between object activities

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#634]
Inhibition(RGS2, GNAQ(activity)) (from REACH) and Inhibition(RGS2, GNAQ(gtpbound)) (from BEL) both get assembled by the EnglishAssembler into "RGS2 inhibits GNAQ," i.e., the object activity (activity vs. gtpbound) is not specified. This leads to confusing results in downstream applications where the two distinct statements actually appear to be identical due to their equivalent English representations.

**Comment by kkaris** [comment]
uuid for the two referenced English statements:
REACH: 2958d048-c66c-4d5c-9b9f-35fd83ced3c0
BEL: f3abe42a-279a-4e8e-b963-991ea0c3ff7e
