### ISSUE TITLE
Add more detail to knowledge sources documentation

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#651]
Now that we have 19 documented knowledge sources, it might make sense to add another intermediate level to the module documentation that separates groups of knowledge sources like:
- general purpose reading systems
- biology-specific reading systems
- standard pathway databases
- custom knowledge bases

See https://indra.readthedocs.io/en/latest/modules/sources/index.html#

**Comment by bgyori** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add an additional level to the indra.sources module documentation](https://trello.com/c/cwBptZqM/30-add-an-additional-level-to-the-indrasources-module-documentation)

**Comment by pagreene** [comment]
Hi level description:

```INDRA can draw content from many sources, some specifically for biological
content, and some for more generic causal knowledge, some are from machine
readers and some are from human-curated or data driven databases.```

Sound good?

**Comment by bgyori** [comment]
Yes, sounds perfect

**Comment by bgyori** [comment]
Done in #695
