### ISSUE TITLE
Resource files should not be version controlled

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#66]
We should have a scripts folder at the top level folder, which contains scripts to create some of the resource files that are now under version control. This includes the different ID mappings: HGNC, UniProt, ChEBI, PubChem, and also the hierarchy RDFs. 
After installing or cloning INDRA, the user could just run a script like

```
python scripts/get_resources.py
```

which would donwload/create the required resource files.

**Comment by jmuhlich** [comment]
We can even put it in the `scripts` arg in `setup.py` so even people who install through pip will get the script installed on their path and made executable. For example:

https://github.com/pysb/pysb/blob/a652ca7b845bbc1b436b160b0af06a2c4b558643/setup.py#L33

**Comment by jmuhlich** [comment]
Also we'll need to think about where the resource files should be downloaded to. The `appdirs` module looks promising.

**Comment by bgyori** [comment]
For now, the resources/update_resources.py script does a good job at keeping things updated.
