### ISSUE TITLE
indra/trips - Could not parse XML string

### ISSUE THREAD

**Issue by remondulos** [sorgerlab/indra#681]
We receive an error when using the function "trips.process_xml()" to load a XML into a trips object
ERROR: [2018-10-30 15:37:08] indra/trips - Could not parse XML string

We used the function trips.process_text() and saved the XML with "save_xml_name". 
Both save_xml_pretty = False/True did not solve the problem.

We validated the XML using a xml validator, but only the save_xml_pretty=False reported a valid xml file.

Could you please help with this issue?

**Comment by bgyori** [comment]
Are you sure you are passing the XML string itself (not the file name) to `trips.process_xml()`? Here is a code sample:
```python
from indra.sources import trips
trips.process_text('EGF binds EGFR', save_xml_name='test.xml')
with open('test.xml', 'r') as fh:
    tp = trips.process_xml(fh.read())
```

**Comment by remondulos** [comment]
Thanks! That solved it! 👍 

I was confused because REACH uses the filename to read a JSON file, that's why I thought TRIPS would also need the filename instead of the text itself.

**Comment by bgyori** [comment]
Okay, great. I might add another API function called `trips.process_xml_file` to make that available also.
