### ISSUE TITLE
Problem with TRIPS query: status code 504

### ISSUE THREAD

**Issue by remondulos** [sorgerlab/indra#688]
trips.process_text() occasionally returns error status code 504

`ERROR: [2018-11-01 13:44:48] indra/trips - Problem with TRIPS query: status code 504`

**Comment by bgyori** [comment]
The TRIPS web service is not equipped to read large amounts of text in a single call. 504 indicates a server-side timeout, and the only way to avoid it is to read smaller chunks of text.
