### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by humehta** [sorgerlab/indra#692]
While executing the following code I am getting the following error:

from indra.sources import bel
from indra.sources import trips
sentence = 'MAP2K1 phosphorylates MAPK3 at Thr-202 and Tyr-204'
trips_processor = trips.process_text(sentence)
print(trips_processor)

Error:
Traceback (most recent call last):
  File "C:/Users/harsh/Desktop/indra.py", line 1, in <module>
    from indra.sources import bel
  File "C:\Users\harsh\Desktop\indra.py", line 1, in <module>
    from indra.sources import bel
ImportError: No module named 'indra.sources'; 'indra' is not a package

Please help.

**Comment by humehta** [comment]
I have done the normal pip install indra as I do for all other packages.
This error says indra is not a package!

**Comment by bgyori** [comment]
Okay, I think then the problem is that you called your script `indra.py` which conflicts with the name of the `indra` package. Try renaming your script and see if it works.

**Comment by humehta** [comment]
Yes that was the problem thanks!

**Comment by humehta** [comment]
I am getting an error for every module on the way .
Indra has installed successfully then also also I am getting an error at each step.
I have to install modules seperately like the following error:
 File "C:/Users/harsh/PycharmProjects/untitled3/testingparalel processing.py", line 1, in <module>
    from indra.sources import bel
  File "C:\Users\harsh\Anaconda3\lib\site-packages\indra\sources\bel\__init__.py", line 1, in <module>
    from .api import process_ndex_neighborhood
  File "C:\Users\harsh\Anaconda3\lib\site-packages\indra\sources\bel\api.py", line 8, in <module>
    from indra.databases import ndex_client
  File "C:\Users\harsh\Anaconda3\lib\site-packages\indra\databases\ndex_client.py", line 10, in <module>
    from ndex2.niceCXNetwork import NiceCXNetwork
ImportError: No module named 'ndex2.niceCXNetwork'

**Comment by bgyori** [comment]
When you `pip install indra`, it comes with a certain set of basic dependencies. However, for various use cases you may need to install additional dependencies, as described here: https://indra.readthedocs.io/en/latest/installation.html#optional-additional-dependencies
In your case, to work with BEL and networks from NDEx, you will need to install
```
pip install indra[bel,ndex]
```
or install the specific packages manually as
```
pip install pybel ndex2==1.2.0.58
```

Depending on what you are trying to do, you might also need to get a copy of a specific BEL corpus (e.g. this one https://github.com/sorgerlab/indra/blob/master/data/large_corpus.bel) to query and point to the file when you call the bel.process_pybel_neighborhood function.

**Comment by humehta** [comment]
Okay.. thanks.
I am executing the above trips demo program and printing the statements given by the trips processor but the program keeps on executing without printing anything?

**Comment by bgyori** [comment]
It's possible that the TRIPS web service is under heavy use right now by other users. Unfortunately there's not much we can do about that with INDRA since it's a third-party service.

**Comment by humehta** [comment]
Okay thanks!!!!

**Comment by bgyori** [comment]
Looks like this is resolved
