### ISSUE TITLE
Trips module very very slow

### ISSUE THREAD

**Issue by humehta** [sorgerlab/indra#704]
Hello,
I am trying to implement the demo TRIPS code in your documentation i seems to take a whole lot of time.
I don't think its because of the TRIPS because I have tried it at different times of the day.
I  think you'll should check it once.

**Comment by bgyori** [comment]
Hi @humehta, I'm sorry to hear that. The TRIPS web service is maintained by a group at IHMC, including @wdebeaum. They have been experiencing very heavy loads from one group using the service, causing issues for everyone else who would want to run smaller batches of reading. Depending on your goals, you could try one of the other reading systems integrated with INDRA, or set up a local instance of TRIPS or another reading system for your project.

**Comment by humehta** [comment]
Okay, no problem.
Thank you for your reply.
