### ISSUE TITLE
Identifiers URL generation for some db_refs entries missing

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#715]
```
WARNING: [2018-11-21 15:16:01] indra/databases - Unhandled name space CHEMBL
WARNING: [2018-11-21 15:16:01] indra/databases - Unhandled name space HMS-LINCS
WARNING: [2018-11-21 15:16:01] indra/databases - Unhandled name space LINCS
WARNING: [2018-11-21 15:16:01] indra/databases - Unhandled name space EGID
WARNING: [2018-11-21 15:16:01] indra/databases - Unhandled name space PCID
```
I highly suspect that PCID is a PUBCHEM entry but has an invalid key from one of the input processors which we should track down.

Update: SFAM and SCHEM from BEL, and SIGNOR are also missing
Update 2: IPR, PFH, NONCODE, LNCRNADB

**Comment by cthoyt** [comment]
EGID is from BEL and represents Entrez Gene identifiers

**Comment by bgyori** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Link out to additional identifiers URLs from indra/databases/__init__.py](https://trello.com/c/OLXiJp1S/56-link-out-to-additional-identifiers-urls-from-indra-databases-initpy)

**Comment by bgyori** [comment]
After some digging, it looks like the PCID entries are coming from Sparser and are actually pointing to PUBCHEM IDs, so we will need to fix this mapping in the processor.

**Comment by bgyori** [comment]
Done in #753
