### ISSUE TITLE
REST API from_hash broken link

### ISSUE THREAD

**Issue by kkaris** [sorgerlab/indra#717]
The badge link (see screenshot) when using the `from_hash` endpoint of the REST API service links out to nothing because it uses a relative URL. The relative URL effectively creates a URL with the address `host.api/statements/from_hash/from_hash/123456?format=html`.

It works fine when using the `from_agents` endpoint, but when linked out to the `from_hashes` endpoint this breaks.

![screenshot](https://user-images.githubusercontent.com/4621351/49111502-45669b00-f25e-11e8-807c-adde6b637127.png)

**Comment by pagreene** [comment]
Your hash is url repeats `from_hash`. It seems to work fine when I link out from an html assembled page.

**Comment by bgyori** [comment]
No but the point is that the page was produced from a from_has query to begin with, hence the repetition.

**Comment by bgyori** [comment]
My suggestion would be to pass in the db_rest_url parameter (https://github.com/sorgerlab/indra/blob/master/indra/assemblers/html/assembler.py#L72-L73) explicitly to avoid this issue.

**Comment by pagreene** [comment]
I see. I misread at first. However I still can't reproduce the actual error. That said, it would be better if the link were absolute.

**Comment by pagreene** [comment]
This is fixed (this was actually an indra_db bug, in this case). Fixed in https://github.com/indralab/indra_db/commit/e7c259eb9c7ebb953bceaf8e89e608fd07273d1f
