### ISSUE TITLE
NDEx network doesn't contain attributes needed by NdexCxProcessor

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#751]
The tests for the NdexCxProcessor are failing. It looks like the network from the web service is returned without meta information that the processor needs. Specifically, there is no `ndexStatus`, `externalId` or `owner` entry in the returned CX, and so these lines error:
```
--> 114         ndex_info = _get_dict_from_list('ndexStatus', self.cx)[0]
    115         self._network_info['externalId'] = ndex_info.get('externalId')
    116         self._network_info['owner'] = ndex_info.get('owner')
```
The tested network here is: http://ndexbio.org/#/network/50e3dff7-133e-11e6-a039-06603eb7f303.
This could be due to an update in the NDEx web service or data model. @agary-ucsd, @dexterpratt, is there perhaps a change on the server side that could cause this?

**Comment by dexterpratt** [comment]
Hi @bgyori , I am passing this to jing. @Agary-ucsd has left the project. :-(

**Comment by jingjingbic** [comment]
@bgyori , We just deployed a new version (2.4.0) of NDEx server to public.ndexbio.org. The ndexStatus is no longer generated by the server. If you need the owner, network UUID etc, you use the "get network summary" function to get those info on the network. If you can send me a longer segment of your code, we can help you to migrate the code to work with the new server.
