### ISSUE TITLE
Dropping Python 2 compatibility

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#760]
Until recently, there were use cases where INDRA was used in a Python 2 environment, however, these use cases have since all been ported to Python 3. Therefore, it seems like there is no scenario anymore where we would need to use INDRA in Python 2. Dropping Python 2 compatibility would allow streamlining new code and making certain I/O operations more efficient (e.g. processing CSV-like files, and using higher protocol pickles).

While the plan isn't to explicitly remove old cross-compatible code, new code added to INDRA would be "allowed" to be Python 3.5+only.

Please raise any comments or concerns on this thread!

**Comment by adarshp** [comment]
Just wanted to chime in to voice my support for this :)

**Comment by cthoyt** [comment]
You have my support!!

**Comment by bgyori** [comment]
If merged, #797 will be the first piece of code that breaks Python 2.x support due to a dependency that is Python 3 only.

**Comment by bgyori** [comment]
Done in release v1.11.
