### ISSUE TITLE
Add table of contents to HTML assembler

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#763]
To make navigating incredibly long pages in the HTML assembler a bit more tractable, it would be nice to use the [Bootstrap Table of Contents plugin](https://afeld.github.io/bootstrap-toc/).

All that would be required is a bit of mucking around in the https://github.com/sorgerlab/indra/blob/master/indra/assemblers/html/template.html file.

**Comment by kkaris** [comment]
I can look at it in Friday when I'm back in the office.

**Comment by kkaris** [comment]
For latest updates on this, checkout: https://github.com/kkaris/indra/tree/html_assembler_toc/indra/assemblers/html

**Comment by bgyori** [comment]
Done in #765
