### ISSUE TITLE
PybelAssembler does not make use of epistemics['direct'] when generating BEL

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#788]
The PybelAssembler currently does not make any use of the evidence.epistemics['direct'] flag when generating BEL, instead generating only directlyIncreases and directlyDecreases relations by default. This should be updated to reflect information about the presence of a physical interaction in the edge when it is available.

@cthoyt Any appetite for tackling this one?

**Comment by cthoyt** [comment]
@johnbachman wilco!
