### ISSUE TITLE
Include citations in indra.sources module documentation

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#803]
Something I had a problem with was trying to figure out what's the correct publication to cite for the data used in `indra.sources.lincs_drug`. Could you include that information in https://github.com/sorgerlab/indra/blob/master/indra/sources/lincs_drug/__init__.py?

Same for `indra.sources.tas` but I think I found it at:

Moret, N., et al. (2018). Cheminformatics tools for analyzing and designing optimized small molecule libraries. BioRxiv, (617), 358978. https://doi.org/10.1101/358978

**Comment by bgyori** [comment]
Thanks, I don't think the LINCS small molecule table has been published but the documentation links out to the table the data is coming from. I added the citation for TAS.
