### ISSUE TITLE
Preassembler bug with Complex order

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#85]
The following should have been merged but weren't:
```
Complex(MED23(), ELK1())
Complex(ELK1(mods: (phosphorylation)), MED23())
```

**Comment by bgyori** [comment]
Added some tests for this and it seems to work fine now, could not reproduce the issue.

**Comment by johnbachman** [comment]
Weird!

On Fri, Jul 29, 2016 at 3:54 PM, Benjamin M. Gyori <notifications@github.com
