### ISSUE TITLE
Bad gateway error biopax

### ISSUE THREAD

**Issue by mariel2017** [sorgerlab/indra#853]
I installed indra following the described procedure. I tried the example in the manual but received the error below. Could you please help me? Thanks. 

```
from indra.sources import biopax
proteins = ['BRAF', 'MAPK3']
limit = 2
biopax_processor = biopax.process_pc_pathsbetween(proteins, limit) 
```
**Output:**
INFO: [2019-04-05 22:17:39] indra.sources.biopax.pathway_commons_client - Sending Pathway Commons query with parameters: 
INFO: [2019-04-05 22:17:39] indra.sources.biopax.pathway_commons_client -  format: BIOPAX
INFO: [2019-04-05 22:17:39] indra.sources.biopax.pathway_commons_client -  organism: 9606
INFO: [2019-04-05 22:17:39] indra.sources.biopax.pathway_commons_client -  datasource: ['wp', 'smpdb', 'reconx', 'reactome', 'psp', 'pid', 'panther', 'netpath', 'msigdb', 'mirtarbase', 'kegg', 'intact', 'inoh', 'humancyc', 'hprd', 'drugbank', 'dip', 'corum']
INFO: [2019-04-05 22:17:39] indra.sources.biopax.pathway_commons_client -  kind: pathsbetween
INFO: [2019-04-05 22:17:39] indra.sources.biopax.pathway_commons_client -  source: BRAF,MAPK3
INFO: [2019-04-05 22:17:39] indra.sources.biopax.pathway_commons_client -  limit: 2
INFO: [2019-04-05 22:17:39] indra.sources.biopax.pathway_commons_client - Sending Pathway Commons query...
ERROR: [2019-04-05 22:17:40] indra.sources.biopax.pathway_commons_client - Response is HTTP code 502.

**Comment by bgyori** [comment]
Hi, that looks like an error in the Pathway Commons web service. I will look into it but there probably isn't much we can do about it other than report it to the maintainers of Pathway Commons.

**Comment by bgyori** [comment]
I just tested it and the same query is working for me. I believe the 502 error from the server was probably a transient issue.

**Comment by mariel2017** [comment]
Yes, I agree and now it is working. Thank you for your help.
