### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by lslflying** [sorgerlab/indra#879]
def get_TR(mat):
        mat_c = mat**2
        if mat_c == mat:
            return mat
        else:
            return get_TR(mat_c)
mat的8次方等于mat的4次方
get_TR(mat**2)   return get_TR(mat**4)
get_TR(mat**4)   return mat**4
当递归结束时应返回mat**4，
但最终的返回结果是mat**4和一个None
请问是为什么呢

**Comment by johnbachman** [comment]
I think you might have posted in the wrong repository?
