### ISSUE TITLE
Duplicated names

### ISSUE THREAD

**Issue by mariel2017** [sorgerlab/indra#908]
I have a list of statements and in this list some agents have identical names but with or without capital. For example, ethanol and Ethanol. The type and identifier are identical. How could I resolve this? 

Thank you very much and kind regards,
Mariel

**Comment by bgyori** [comment]
There are a number of procedures in INDRA that operate over INDRA Statements and assemble/aggregate knowledge in various ways. A simple way to access these is via the `indra.tools.assemble_corpus` module. There is a component called the `GroundingMapper` which fixes common errors in assigning identifiers to Agents, and standardizes the names of Agents based on identifiers. You can call it on a list of Statements (stmts) as:
```
import indra.tools.assemble_corpus as ac
stmts = ac.map_grounding(stmts)
```
in the result, the names of Agents like ethanol/Ethanon will be standardized wherever possible.

**Comment by mariel2017** [comment]
Thank you very much for the information.
I tried with the function map_grounding but it is not solving the issue (e.g. benzene/Benzene). I dumped the statements into the attached file.
[stmts_grounded.txt](https://github.com/sorgerlab/indra/files/3392402/stmts_grounded.txt)

**Comment by bgyori** [comment]
I just tested your statements and I am getting the right result (e.g., benzene is always lower-case), so I suspect you need to update your INDRA version to get the latest changes. Since the latest code hasn't yet been released on PyPI, you can update it as follows:
```
pip install -U git+https://github.com/sorgerlab/indra.git
```

**Comment by mariel2017** [comment]
Ok, that is good to know. Thanks, I will update INDRA to get the latest changes.

**Comment by bgyori** [comment]
I think this has been resolved so I'm closing the issue
