### ISSUE TITLE
Name standardization for all entities

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#92]
Currently only proteins have names canonicalized to HGNC gene symbols. Similar renaming should occur for biological processes and chemicals.

**Comment by bgyori** [comment]
This is especially important because misgrounded entities are often standardized by the input processors (TRIPS, REACH) and if the grounding map doesn't fix these, the wrong names remain. Example: ROS1 remains as a name even though the entity was mapped to ROS.

**Comment by bgyori** [comment]
#150 is related, maybe duplicate

**Comment by bgyori** [comment]
Closing this because we can separate it into multiple individual issues.
