### ISSUE TITLE
Query MeSH with requests

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#931]
https://github.com/sorgerlab/indra/blob/e10e898e0868d85a0243f4e58ad3c6c0fbc1a1ab/indra/databases/mesh_client.py#L165-L170

I think the correct keyword argument is `params`. Reference: https://2.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls

Alternative:
```python
resp = requests.get(url, params=args)
```

**Comment by bgyori** [comment]
Sure, we can change to that as long as it works in practice.

**Comment by bgyori** [comment]
Fixed in #940
