### ISSUE TITLE
Eidos timex parsing fails

### ISSUE THREAD

**Issue by brandomr** [sorgerlab/indra#934]
## Summary

With the latest version of [Eidos](https://github.com/clulab/eidos) (built from `master` branch) INDRA fails to process sentences with time extractions.

## Recreating the error

Try the following after running the [Eidos webapp](https://github.com/clulab/eidos#webapp), which should be available at `http://localhost:9000`:

```
from indra.sources import eidos

text = """A significant increase in precipitation resulted in food insecurity 
          and a decrease in humanitarian interventions in South Sudan in 1997."""

ep = eidos.process_text(text, webservice='http://localhost:9000')
```
This returns `KeyError: 'duration'` pointing at this [line in INDRA](https://github.com/sorgerlab/indra/blob/43f92c7ae76946bd9ce485a260cf0c41d7689655/indra/sources/eidos/processor.py#L423). 

## Potential Resolution

The latest JSON-LD provided by Eidos does not have a `duration` key for its time extractions. These time extractions take this form:

```
[{'endOffset': 146,
  'intervals': [{'@type': 'TimeInterval',
    '@id': '_:TimeInterval_1',
    'start': '1997-01-01T00:00',
    'end': '1998-01-01T00:00'}],
  'text': '1997',
  'startOffset': 142,
  '@type': 'TimeExpression',
  '@id': '_:TimeExpression_1'}]
```

The duration could be calculated by INDRA (instead of Eidos) by subtracting `start` from `end` within the timex.

cc @kwalcock

**Comment by kwalcock** [comment]
Yes, it is the case that durations are now gone in master.  They were still present in the recent run we did for Ethiopia.  We could have made the change clearer.  See also https://github.com/clulab/eidos/wiki/JSON-LD where duration is crossed out and https://github.com/clulab/eidos/pull/632.  Anyone just holler if you run into problems with all these moving parts.

**Comment by bgyori** [comment]
Thanks for the detailed report! I can fix this today and make a new release as soon as possible.
