### ISSUE TITLE
Use BE families/complexes in BEL processor

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#96]
BEL statements often involve protein families defined in the BEL namespace. Need to map BEL named families to families in the bioentities namespace (where possible) and ground the statements to the appropriate bioentities ID.

Also need to get enumerated list of BEL protein families, compare against bioentities names, and unify them if possible.

Same for protein complexes.

**Comment by bgyori** [comment]
http://resource.belframework.org/belframework/1.0/resource/

**Comment by bgyori** [comment]
Done
