### ISSUE TITLE
Changed "shared name" caused all nodes to be renamed

### ISSUE THREAD

**Issue by MargieWilke** [sorgerlab/indra#963]
I wanted to change the name of a node in the Node Table.  I changed the name in the "shared name" column.  This caused all the nodes to change to the same name.  Fortunately the edge table was not affected.  My deepest apologies if I edited the wrong column!

**Comment by bgyori** [comment]
Hi @MargieWilke, are you sure this is an INDRA issue?

**Comment by MargieWilke** [comment]
Good thing I was humble about it! It is a Cytoscape issue!
Thank you for your patience!
Margie

**Comment by bgyori** [comment]
No problem :)
